/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import FormalConjecturesUtil

/-!
# The Gerstenhaber problem for three commuting matrices

Gerstenhaber proved in 1961 [Ger61] that the unital algebra generated by two commuting
$n \times n$ matrices over a field has dimension at most $n$. It is an open problem,
known as the **Gerstenhaber problem**, whether the same bound holds for three pairwise
commuting matrices. The bound fails for four or more pairwise commuting matrices.

*References:*
- [Ger61] M. Gerstenhaber, *On dominance and varieties of commuting matrices*.
  Annals of Mathematics (2) 73 (1961), no. 2, 324–348.
  https://doi.org/10.2307/1970336
- [arXiv:2402.16334](https://arxiv.org/abs/2402.16334), M. Satriano and W. Zhang,
  *On the algebra generated by three commuting matrices: combinatorial cases*.
- [arXiv:2006.08588](https://arxiv.org/abs/2006.08588), J. Holbrook and M. Omladič,
  *A computing strategy and programs to resolve the Gerstenhaber Problem for
  commuting triples of matrices*.
-/

@[expose] public section

namespace Gerstenhaber

variable {K : Type*} [Field K] {n : ℕ}


-- ============================================================
-- Helper lemmas for the proof of `finrank_adjoin_pair_le`.
-- ============================================================

open Matrix in
noncomputable def linAlgEquiv (K : Type*) [Field K] (n : ℕ) :
    Matrix (Fin n) (Fin n) K ≃ₐ[K] Module.End K (Fin n → K) :=
  Matrix.toLinAlgEquiv (Pi.basisFun K (Fin n))

open Matrix in
lemma finrank_adjoin_transfer (A B : Matrix (Fin n) (Fin n) K) :
    Module.finrank K (Algebra.adjoin K ({A, B} : Set (Matrix (Fin n) (Fin n) K))) =
      Module.finrank K (Algebra.adjoin K
        ({linAlgEquiv K n A, linAlgEquiv K n B} : Set (Module.End K (Fin n → K)))) := by
  let e : Matrix (Fin n) (Fin n) K ≃ₐ[K] Module.End K (Fin n → K) := linAlgEquiv K n
  have hmap : Subalgebra.map e.toAlgHom (Algebra.adjoin K ({A, B} : Set (Matrix (Fin n) (Fin n) K))) =
      Algebra.adjoin K ({e A, e B} : Set (Module.End K (Fin n → K))) := by
    rw [AlgHom.map_adjoin]
    simp [Set.image_pair, e]
  have hfin : Module.finrank K (Subalgebra.map e.toAlgHom (Algebra.adjoin K ({A, B} : Set (Matrix (Fin n) (Fin n) K)))) =
      Module.finrank K (Algebra.adjoin K ({A, B} : Set (Matrix (Fin n) (Fin n) K))) := by
    exact (LinearEquiv.finrank_eq (e.subalgebraMap (Algebra.adjoin K ({A, B} : Set (Matrix (Fin n) (Fin n) K)))).toLinearEquiv).symm
  rw [← hmap, ← hfin]

open scoped BigOperators in
lemma linearIndependent_scalarExt_matrix {K L : Type*} [Field K] [Field L] [Algebra K L] {n : ℕ} {ι : Type*}
    {v : ι → Matrix (Fin n) (Fin n) K}
    (hli : LinearIndependent K v) :
    LinearIndependent L (fun i : ι => (v i).map (algebraMap K L)) := by
  classical
  let bL : Module.Basis (Module.Basis.ofVectorSpaceIndex K L) K L := Module.Basis.ofVectorSpace K L
  rw [linearIndependent_iff] at hli ⊢
  intro g hg
  let c : ι → (Module.Basis.ofVectorSpaceIndex K L) →₀ K := fun i => bL.repr (g i)
  have hrepr : ∀ i : ι, g i = (Finsupp.linearCombination K (fun γ => bL γ)) (c i) := by
    intro i
    rw [← Module.Basis.repr_symm_apply]
    simp [c]
  have hc : ∀ i : ι, c i = 0 := by
    intro i
    apply Finsupp.ext
    intro γ
    have hcoef : ∀ a b : Fin n, (∑ j ∈ g.support, (c j γ) • (v j a b)) = 0 := by
      intro a b
      have hgb : (∑ j ∈ g.support, g j • (algebraMap K L (v j a b))) = 0 := by
        have := congrArg (fun M : Matrix (Fin n) (Fin n) L => M a b) hg
        simpa [Finsupp.linearCombination_apply, Finsupp.sum_apply, Finsupp.sum,
          Matrix.sum_apply, Matrix.map_apply, Pi.smul_apply, smul_eq_mul] using this
      have hre : (bL.repr (∑ j ∈ g.support, g j • (algebraMap K L (v j a b)))) = 0 := by
        rw [hgb]
        simp
      have hre' : (∑ j ∈ g.support, bL.repr (g j • (algebraMap K L (v j a b)))) = 0 := by
        exact (map_sum (bL.repr) (fun j => g j • (algebraMap K L (v j a b))) g.support).symm.trans hre
      have hper : ∀ j : ι, bL.repr (g j • (algebraMap K L (v j a b))) = (v j a b) • bL.repr (g j) := by
        intro j
        rw [smul_eq_mul, mul_comm]
        rw [← Algebra.smul_def]
        rw [map_smul]
      rw [Finset.sum_congr rfl (fun j hj => hper j)] at hre'
      have hγ : (∑ j ∈ g.support, (v j a b) • c j) γ = 0 := by
        have := congrArg (fun f : (Module.Basis.ofVectorSpaceIndex K L) →₀ K => f γ) hre'
        simpa [c, Finsupp.coe_zero, Finsupp.coe_finset_sum, Finsupp.coe_smul, Pi.smul_apply] using this
      have hγ' : (∑ j ∈ g.support, (v j a b) • (c j γ)) = 0 := by
        simpa [Finsupp.coe_finset_sum, Finsupp.coe_smul, Pi.smul_apply] using hγ
      simpa [mul_comm] using hγ'
    have hmat : (∑ j ∈ g.support, (c j γ) • v j) = 0 := by
      ext a b
      simpa [Matrix.sum_apply, Matrix.smul_apply] using hcoef a b
    let cγ : ι →₀ K := Finsupp.onFinset g.support (fun j => c j γ) (by
      intro j hj
      by_contra hnot
      have hgj0 : g j = 0 := by
        by_contra hg
        exact hnot (Finsupp.mem_support_iff.mpr hg)
      have hcj0 : c j = 0 := by
        simp [c, hgj0]
      exact hj (by simpa [hcj0]))
    have hcomb : (Finsupp.linearCombination K v) cγ = 0 := by
      rw [Finsupp.linearCombination_apply, Finsupp.sum]
      have hsupp : cγ.support ⊆ g.support := by
        simpa [cγ] using (Finsupp.support_onFinset_subset : (Finsupp.onFinset g.support (fun j => c j γ) _).support ⊆ g.support)
      rw [Finset.sum_subset hsupp (by
        intro j hj hn
        have hz : cγ j = 0 := by
          by_contra hzj
          exact hn (Finsupp.mem_support_iff.mpr hzj)
        simp [hz])]
      simpa [cγ, mul_comm] using hmat
    have hzero : cγ = 0 := hli cγ hcomb
    have hciγ : c i γ = 0 := by
      have := congrArg (fun f : ι →₀ K => f i) hzero
      simpa [cγ] using this
    simpa [c] using hciγ
  ext i
  have : g i = 0 := by
    rw [hrepr i, hc i]
    simp
  exact this

set_option maxHeartbeats 800000 in
open scoped BigOperators in
lemma finrank_baseChange_le {K L : Type*} [Field K] [Field L] [Algebra K L] {n : ℕ}
    (A B : Matrix (Fin n) (Fin n) K) :
    Module.finrank K (Algebra.adjoin K ({A, B} : Set (Matrix (Fin n) (Fin n) K))) ≤
      Module.finrank L (Algebra.adjoin L
        ({A.map (algebraMap K L), B.map (algebraMap K L)} : Set (Matrix (Fin n) (Fin n) L))) := by
  let φ : Matrix (Fin n) (Fin n) K →ₐ[K] Matrix (Fin n) (Fin n) L := (Algebra.ofId K L).mapMatrix
  have hφ : ∀ M : Matrix (Fin n) (Fin n) K, φ M = M.map (algebraMap K L) := by
    intro M
    rfl
  let W := Algebra.adjoin K ({A, B} : Set (Matrix (Fin n) (Fin n) K))
  let b : Module.Basis (Module.Basis.ofVectorSpaceIndex K W) K W := Module.Basis.ofVectorSpace K W
  letI : Fintype (Module.Basis.ofVectorSpaceIndex K W) := Fintype.ofFinite _
  let ι := Module.Basis.ofVectorSpaceIndex K W
  let U : Submodule L (Matrix (Fin n) (Fin n) L) :=
    Submodule.span L (Set.range (fun i : ι => φ (b i)))
  have hmem : ∀ i : ι, φ (b i) ∈ U := fun i => Submodule.subset_span (by simp)
  have hliW : LinearIndependent K (fun i : ι => ((b i : W) : Matrix (Fin n) (Fin n) K)) := by
    have hb := b.linearIndependent
    rw [linearIndependent_iff] at hb ⊢
    intro f hf
    apply hb
    apply Subtype.ext
    simpa [Finsupp.linearCombination_apply, Finsupp.sum, map_sum, map_smul] using hf
  have hli0 : LinearIndependent L (fun i : ι => ((b i : W) : Matrix (Fin n) (Fin n) K).map (algebraMap K L)) :=
    linearIndependent_scalarExt_matrix hliW
  have hliφ : LinearIndependent L (fun i : ι => φ (b i)) := by
    simpa [hφ] using hli0
  have hliU : LinearIndependent L (fun i : ι => (⟨φ (b i), hmem i⟩ : U)) := by
    rw [linearIndependent_iff] at hliφ ⊢
    intro f hf
    have hf' := congrArg (Submodule.subtype U) hf
    have hsimp : (Submodule.subtype U) (Finsupp.linearCombination L (fun i : ι => (⟨φ (b i), hmem i⟩ : U)) f) =
        Finsupp.linearCombination L (fun i : ι => φ (b i)) f := by
      rw [Finsupp.linearCombination_apply, Finsupp.linearCombination_apply]
      simp [Finsupp.sum, map_sum, map_smul, Submodule.subtype_apply]
    exact hliφ f (by simpa [hsimp] using hf')
  have hspanU : ⊤ ≤ Submodule.span L (Set.range (fun i : ι => (⟨φ (b i), hmem i⟩ : U))) := by
    intro x hx
    have hx' : (x : Matrix (Fin n) (Fin n) L) ∈ Submodule.span L (Set.range (fun i : ι => φ (b i))) := by
      simpa [U] using x.property
    have hr : Set.range (fun i : ι => φ (b i)) =
        (Submodule.subtype U) '' Set.range (fun i : ι => (⟨φ (b i), hmem i⟩ : U)) := by
      rw [← Set.range_comp]
      rfl
    have hU : Submodule.span L (Set.range (fun i : ι => φ (b i))) =
        (Submodule.span L (Set.range (fun i : ι => (⟨φ (b i), hmem i⟩ : U)))).map (Submodule.subtype U) := by
      rw [hr]
      rw [Submodule.map_span]
    rw [hU] at hx'
    rcases hx' with ⟨y, hy, hxy⟩
    have hyx : y = x := Subtype.ext hxy
    simpa [hyx] using hy
  let bU : Module.Basis ι L U := Module.Basis.mk hliU hspanU
  have hfinU : Module.finrank L U = Module.finrank K W := by
    rw [Module.finrank_eq_card_basis bU, Module.finrank_eq_card_basis b]
  have hmap : (Algebra.adjoin K ({A, B} : Set (Matrix (Fin n) (Fin n) K))).map φ ≤
      (Algebra.adjoin L ({φ A, φ B} : Set (Matrix (Fin n) (Fin n) L))).restrictScalars K := by
    rw [AlgHom.map_adjoin, Set.image_pair]
    exact Algebra.adjoin_le (by rintro x (rfl | rfl) <;> exact Algebra.subset_adjoin (by simp))
  have hUle : U ≤ (Algebra.adjoin L
      ({A.map (algebraMap K L), B.map (algebraMap K L)} : Set (Matrix (Fin n) (Fin n) L))).toSubmodule := by
    rw [Submodule.span_le]
    rintro x hx
    rcases hx with ⟨i, rfl⟩
    have hφbi : φ (b i) ∈ (Algebra.adjoin K ({A, B} : Set (Matrix (Fin n) (Fin n) K))).map φ := by
      exact Subalgebra.mem_map.mpr ⟨b i, by simp [W], rfl⟩
    exact hmap hφbi
  have hfin_le : Module.finrank L U ≤ Module.finrank L (Algebra.adjoin L
      ({A.map (algebraMap K L), B.map (algebraMap K L)} : Set (Matrix (Fin n) (Fin n) L))) := by
    exact Submodule.finrank_mono hUle
  rw [← hfinU]
  exact hfin_le

namespace TwoBlock

variable {K : Type*} [Field K] {V : Type*} [AddCommGroup V] [Module K V] [FiniteDimensional K V]

-- endomorphisms that map a submodule into itself form a K-subalgebra
def stabilizer (W : Submodule K V) : Subalgebra K (Module.End K V) where
  carrier := {T | ∀ x ∈ W, T x ∈ W}
  zero_mem' := by
    intro x hx
    simp
  add_mem' := by
    intro X Y hX hY x hx
    exact W.add_mem (hX x hx) (hY x hx)
  one_mem' := by
    intro x hx
    simpa
  mul_mem' := by
    intro X Y hX hY x hx
    exact hX (Y x) (hY x hx)
  algebraMap_mem' := by
    intro c x hx
    have : (algebraMap K (Module.End K V) c) x = c • x := by rfl
    rw [this]
    exact W.smul_mem c hx

-- elements of adjoin {A,B} preserve K0 (a submodule stabilized by A and B)
lemma mem_adjoin_preserves {A B : Module.End K V} {K0 : Submodule K V}
    (hAK : ∀ x ∈ K0, A x ∈ K0) (hBK : ∀ x ∈ K0, B x ∈ K0) :
    ∀ X ∈ Algebra.adjoin K ({A, B} : Set (Module.End K V)), ∀ x ∈ K0, (X : Module.End K V) x ∈ K0 := by
  intro X hX x hx
  have hle : Algebra.adjoin K ({A, B} : Set (Module.End K V)) ≤ stabilizer K0 := by
    exact Algebra.adjoin_le (by
      rintro Y (rfl | rfl)
      · exact hAK
      · exact hBK)
  exact hle hX x hx

-- restriction to a stable submodule is an algebra hom on the stabilizer
noncomputable def restrictAlgHom (W : Submodule K V) :
    TwoBlock.stabilizer W →ₐ[K] Module.End K W where
  toFun := fun X => X.1.restrict X.2
  map_zero' := by
    ext x
    simp [Subalgebra.coe_zero, LinearMap.restrict_apply, LinearMap.zero_apply]
  map_one' := by
    ext x
    simp [Subalgebra.coe_one, LinearMap.restrict_apply, map_one]
  map_add' := by
    intro X Y
    ext x
    simp only [Subalgebra.coe_add, LinearMap.restrict_apply, Subtype.coe_mk]
    rfl
  map_mul' := by
    intro X Y
    ext x
    simp only [Subalgebra.coe_mul, LinearMap.restrict_apply, Subtype.coe_mk]
    rfl
  commutes' := by
    intro c
    ext x
    simp [LinearMap.restrict_apply]

-- the two-block bound: V = K0 ⊕ R0, A,B preserve both ⟹ finrank adjoin ≤ sum
set_option maxHeartbeats 4000000 in
lemma finrank_twoBlock (A B : Module.End K V) (hAB : Commute A B)
    {K0 R0 : Submodule K V} (hcomp : IsCompl K0 R0)
    (hAK : ∀ x ∈ K0, A x ∈ K0) (hBK : ∀ x ∈ K0, B x ∈ K0)
    (hAR : ∀ x ∈ R0, A x ∈ R0) (hBR : ∀ x ∈ R0, B x ∈ R0) :
    Module.finrank K (Algebra.adjoin K ({A, B} : Set (Module.End K V))) ≤
      Module.finrank K (Algebra.adjoin K
        ({A.restrict hAK, B.restrict hBK} : Set (Module.End K K0))) +
        Module.finrank K (Algebra.adjoin K
          ({A.restrict hAR, B.restrict hBR} : Set (Module.End K R0))) := by
  classical
  let S := TwoBlock.stabilizer K0
  let ρ : S →ₐ[K] Module.End K K0 := restrictAlgHom K0
  have hA_in : A ∈ S := hAK
  have hB_in : B ∈ S := hBK
  let p : Subalgebra K (Module.End K K0) :=
    Algebra.adjoin K ({A.restrict hAK, B.restrict hBK} : Set (Module.End K K0))
  let q : Subalgebra K (Module.End K R0) :=
    Algebra.adjoin K ({A.restrict hAR, B.restrict hBR} : Set (Module.End K R0))
  have himK : ∀ {X : Module.End K V} (hX : X ∈ Algebra.adjoin K ({A, B} : Set (Module.End K V))),
      X.restrict (mem_adjoin_preserves hAK hBK X hX) ∈ p := by
    intro X hX
    have hXst : X ∈ S := mem_adjoin_preserves hAK hBK X hX
    let Z : S := ⟨X, hXst⟩
    have hZ : Z ∈ Algebra.adjoin K ({⟨A, hA_in⟩, ⟨B, hB_in⟩} : Set S) := by
      have hmap : (Algebra.adjoin K ({⟨A, hA_in⟩, ⟨B, hB_in⟩} : Set S)).map S.val =
          Algebra.adjoin K ({A, B} : Set (Module.End K V)) := by
        rw [AlgHom.map_adjoin, Set.image_pair]
        rfl
      have hXmap : X ∈ (Algebra.adjoin K ({⟨A, hA_in⟩, ⟨B, hB_in⟩} : Set S)).map S.val := by
        rw [hmap]
        exact hX
      rw [Subalgebra.mem_map] at hXmap
      rcases hXmap with ⟨Y, hY, hYval⟩
      have hZY : Z = Y := Subtype.ext hYval.symm
      simpa [hZY] using hY
    have him : ρ Z ∈ Algebra.adjoin K ({ρ ⟨A, hA_in⟩, ρ ⟨B, hB_in⟩} : Set (Module.End K K0)) := by
      have hma := AlgHom.map_adjoin ρ ({⟨A, hA_in⟩, ⟨B, hB_in⟩} : Set S)
      have hρmem : ρ Z ∈ (Algebra.adjoin K ({⟨A, hA_in⟩, ⟨B, hB_in⟩} : Set S)).map ρ := by
        exact Subalgebra.mem_map.mpr ⟨Z, hZ, rfl⟩
      rw [hma, Set.image_pair] at hρmem
      simpa using hρmem
    have hρZ : ρ Z = X.restrict (mem_adjoin_preserves hAK hBK X hX) := rfl
    have hρA : ρ ⟨A, hA_in⟩ = A.restrict hAK := rfl
    have hρB : ρ ⟨B, hB_in⟩ = B.restrict hBK := rfl
    simpa [p, hρZ, hρA, hρB] using him
  have himR : ∀ {X : Module.End K V} (hX : X ∈ Algebra.adjoin K ({A, B} : Set (Module.End K V))),
      X.restrict (mem_adjoin_preserves hAR hBR X hX) ∈ q := by
    intro X hX
    -- mirror of himK with R0
    have hXst : X ∈ TwoBlock.stabilizer R0 := mem_adjoin_preserves hAR hBR X hX
    let Z : TwoBlock.stabilizer R0 := ⟨X, hXst⟩
    let ρR : TwoBlock.stabilizer R0 →ₐ[K] Module.End K R0 := restrictAlgHom R0
    have hA_inR : A ∈ TwoBlock.stabilizer R0 := hAR
    have hB_inR : B ∈ TwoBlock.stabilizer R0 := hBR
    have hZ : Z ∈ Algebra.adjoin K ({⟨A, hA_inR⟩, ⟨B, hB_inR⟩} : Set (TwoBlock.stabilizer R0)) := by
      have hmap : (Algebra.adjoin K ({⟨A, hA_inR⟩, ⟨B, hB_inR⟩} : Set (TwoBlock.stabilizer R0))).map
          (TwoBlock.stabilizer R0).val =
          Algebra.adjoin K ({A, B} : Set (Module.End K V)) := by
        rw [AlgHom.map_adjoin, Set.image_pair]
        rfl
      have hXmap : X ∈ (Algebra.adjoin K ({⟨A, hA_inR⟩, ⟨B, hB_inR⟩} : Set (TwoBlock.stabilizer R0))).map
          (TwoBlock.stabilizer R0).val := by
        rw [hmap]
        exact hX
      rw [Subalgebra.mem_map] at hXmap
      rcases hXmap with ⟨Y, hY, hYval⟩
      have hZY : Z = Y := Subtype.ext hYval.symm
      simpa [hZY] using hY
    have him : ρR Z ∈ Algebra.adjoin K ({ρR ⟨A, hA_inR⟩, ρR ⟨B, hB_inR⟩} : Set (Module.End K R0)) := by
      have hma := AlgHom.map_adjoin ρR ({⟨A, hA_inR⟩, ⟨B, hB_inR⟩} : Set (TwoBlock.stabilizer R0))
      have hρmem : ρR Z ∈ (Algebra.adjoin K ({⟨A, hA_inR⟩, ⟨B, hB_inR⟩} : Set (TwoBlock.stabilizer R0))).map ρR := by
        exact Subalgebra.mem_map.mpr ⟨Z, hZ, rfl⟩
      rw [hma, Set.image_pair] at hρmem
      simpa using hρmem
    have hρZ : ρR Z = X.restrict (mem_adjoin_preserves hAR hBR X hX) := rfl
    have hρA : ρR ⟨A, hA_inR⟩ = A.restrict hAR := rfl
    have hρB : ρR ⟨B, hB_inR⟩ = B.restrict hBR := rfl
    simpa [q, hρZ, hρA, hρB] using him
  -- the map into the product of adjoins
  let ψ : (Algebra.adjoin K ({A, B} : Set (Module.End K V))) →ₗ[K] (p × q) :=
    { toFun := fun X => (⟨X.1.restrict (mem_adjoin_preserves hAK hBK X.1 X.2), himK X.2⟩,
        ⟨X.1.restrict (mem_adjoin_preserves hAR hBR X.1 X.2), himR X.2⟩)
      map_add' := by
        intro X Y
        ext <;> simp [LinearMap.restrict_apply]
      map_smul' := by
        intro c X
        ext <;> simp [LinearMap.restrict_apply] }
  have hψinj : Function.Injective ψ := by
    intro X Y hXY
    apply Subtype.ext
    ext v
    have hXY1 : (ψ X).1.val = (ψ Y).1.val := congrArg (fun z : p × q => (z.1.val : Module.End K K0)) hXY
    have hXY2 : (ψ X).2.val = (ψ Y).2.val := congrArg (fun z : p × q => (z.2.val : Module.End K R0)) hXY
    have hsup : ⊤ ≤ K0 ⊔ R0 := by
      rw [hcomp.codisjoint.eq_top]
    have hv : v ∈ K0 ⊔ R0 := hsup (by trivial)
    rw [Submodule.mem_sup] at hv
    rcases hv with ⟨k, hk, r, hr, hkr⟩
    rw [← hkr]
    rw [map_add]
    have hK : X.1 k = Y.1 k := by
      have := congrArg (fun f : Module.End K K0 => f ⟨k, hk⟩) hXY1
      simpa [ψ, LinearMap.restrict_apply] using this
    have hR : X.1 r = Y.1 r := by
      have := congrArg (fun f : Module.End K R0 => f ⟨r, hr⟩) hXY2
      simpa [ψ, LinearMap.restrict_apply] using this
    rw [hK, hR]
    rw [map_add]
  have hfin_eq : Module.finrank K (Algebra.adjoin K ({A, B} : Set (Module.End K V))) =
      Module.finrank K (LinearMap.range ψ) := by
    exact LinearEquiv.finrank_eq (LinearEquiv.ofInjective ψ hψinj)
  have hfin_le : Module.finrank K (LinearMap.range ψ) ≤
      Module.finrank K (p × q) := by
    exact Submodule.finrank_le (LinearMap.range ψ)
  haveI : Module.Free K p := Module.Free.of_basis (Module.Basis.ofVectorSpace K p)
  haveI : Module.Free K q := Module.Free.of_basis (Module.Basis.ofVectorSpace K q)
  haveI : Module.Finite K p := by infer_instance
  haveI : Module.Finite K q := by infer_instance
  haveI : Module.Finite K (p × q) := by infer_instance
  rw [hfin_eq]
  rw [← Module.finrank_prod]
  exact hfin_le

end TwoBlock

namespace L2

universe u

open scoped BigOperators

open Polynomial

lemma isCompl_split {R : Type*} [Ring R] {W : Type u} [AddCommGroup W] [Module R W]
    {r : ℕ} (G : Fin r → Submodule R W) (j : Fin r)
    (hIndep : iSupIndep G) (hSup : ⨆ i : Fin r, G i = ⊤) :
    IsCompl (⨆ i ∈ {i : Fin r | i < j}, G i) (⨆ i ∈ {i : Fin r | j ≤ i}, G i) := by
  constructor
  · exact hIndep.disjoint_biSup_biSup (s := {i : Fin r | i < j}) (t := {i : Fin r | j ≤ i}) (by
      rw [Set.disjoint_left]
      intro x hxs hxt
      exact (lt_irrefl j) (lt_of_le_of_lt hxt hxs))
  · rw [Codisjoint]
    intro c hc₁ hc₂
    have hsplit : (⨆ i : Fin r, G i) = (⨆ i ∈ {i : Fin r | i < j}, G i) ⊔ (⨆ i ∈ {i : Fin r | j ≤ i}, G i) := by
      apply le_antisymm
      · exact iSup_le (fun i => by
          rcases lt_or_ge i j with hij | hji
          · exact le_trans (le_iSup₂ (f := fun a ha => G a) i hij) le_sup_left
          · exact le_trans (le_iSup₂ (f := fun a ha => G a) i hji) le_sup_right)
      · exact sup_le (iSup₂_le_iff.mpr (fun i hi => le_iSup (fun i : Fin r => G i) i))
          (iSup₂_le_iff.mpr (fun i hi => le_iSup (fun i : Fin r => G i) i))
    rw [← hSup, hsplit]
    exact sup_le hc₁ hc₂

lemma ofIsCompl_range_subset {R : Type*} [Ring R] {E : Type u} [AddCommGroup E] [Module R E]
    {p q : Submodule R E} (h : IsCompl p q) :
    ∀ w : E, ((1 - LinearMap.ofIsCompl h p.subtype 0) : E →ₗ[R] E) w ∈ q := by
  intro w
  have hπ₂ : (1 - LinearMap.ofIsCompl h p.subtype 0 : E →ₗ[R] E) = LinearMap.ofIsCompl h 0 q.subtype := by
    exact (LinearMap.ofIsCompl_eq h (φ := (0 : p →ₗ[R] E)) (ψ := q.subtype)
      (χ := (1 - LinearMap.ofIsCompl h p.subtype 0 : E →ₗ[R] E)) (by
        intro u
        simp [LinearMap.ofIsCompl_apply_left])
      (by
        intro v
        simp [LinearMap.ofIsCompl_apply_right])).symm
  rw [hπ₂]
  rw [LinearMap.ofIsCompl_eq_add h]
  simp

lemma pow_sub_sum {E : Type*} [Ring E] (x y : E) (n : ℕ) :
    x ^ n - y ^ n = ∑ l : Fin n, x ^ (n - 1 - l.val) * (x - y) * y ^ l.val := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ', pow_succ']
      rw [show x * x ^ n - y * y ^ n = x * (x ^ n - y ^ n) + (x - y) * y ^ n by
        rw [mul_sub, sub_mul]
        abel]
      rw [ih]
      rw [Fin.sum_univ_castSucc]
      rw [Finset.mul_sum]
      congr 1
      · apply Finset.sum_congr rfl
        intro l hl
        have hx : x * x ^ (n - 1 - l.val) = x ^ (n - l.val) := by
          rw [← pow_succ']
          congr 1
          omega
        rw [← mul_assoc, ← mul_assoc, hx]
        simpa
      · have hlast : x ^ (n - (Fin.last n).val) * (x - y) * y ^ (Fin.last n).val = (x - y) * y ^ n := by
          simp
        simp [hlast]

lemma spanFinrank_le_card {K : Type*} [Semiring K] {W : Type u} [AddCommMonoid W] [Module K W]
    {j : ℕ} (gens : Fin j → W) :
    (Submodule.span K (Set.range gens)).spanFinrank ≤ j := by
  exact (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range gens)).trans (by
    rw [← Set.image_univ]
    exact (Set.ncard_image_le (s := Set.univ) (f := gens) Set.finite_univ).trans (by simp))

lemma leading_L1 {K : Type*} [Field K] {W : Type u} [AddCommGroup W]
    [Module (Polynomial K) W] [Module K W] [IsScalarTower K (Polynomial K) W]
    [Module.Finite K W]
    {j : ℕ} (T : Module.End (Polynomial K) W) (V₁ : Submodule (Polynomial K) W)
    (hT : ∀ w ∈ V₁, T w ∈ V₁)
    (gens : Fin j → W) (hgen : V₁ = Submodule.span (Polynomial K) (Set.range gens)) :
    ∃ c : Fin j → (Polynomial K),
      ∀ w ∈ V₁, (T ^ j) w = ∑ m : Fin j, (c m) • ((T ^ m.val) w) := by
  classical
  have hfin : Module.Finite (Polynomial K) ↥V₁ := by
    have hK : Module.Finite K ↥V₁ := by
      exact Module.Finite.of_injective (V₁.subtype : ↥V₁ →ₗ[K] W) (Submodule.injective_subtype V₁)
    exact Module.Finite.of_restrictScalars_finite K (Polynomial K) ↥V₁
  let T₁ : Module.End (Polynomial K) ↥V₁ := T.restrict (by
    intro w hw
    exact hT w hw)
  rcases LinearMap.exists_monic_and_coeff_mem_pow_and_aeval_eq_zero_of_range_le_smul
    (M := ↥V₁) (R := Polynomial K) (f := T₁) (I := ⊤) (by simp) with ⟨p, hp_monic, hp_deg, _, hp_aeval⟩
  let d : ℕ := p.natDegree
  have hd : d ≤ j := by
    dsimp [d]
    rw [hp_deg]
    let emb : Fin j → ↥V₁ := fun i => ⟨gens i, by
      rw [hgen]; exact Submodule.subset_span (Set.mem_range_self i)⟩
    have htop : (⊤ : Submodule (Polynomial K) ↥V₁) = Submodule.span (Polynomial K) (Set.range emb) := by
      apply le_antisymm
      · intro x hx
        rw [Submodule.mem_span]
        intro N hN
        have hx1 : (x : W) ∈ Submodule.span (Polynomial K) (Set.range gens) := by
          rw [← hgen]
          exact x.2
        have hle : Submodule.span (Polynomial K) (Set.range gens) ≤ Submodule.map V₁.subtype N := by
          rw [Submodule.span_le]
          rintro w ⟨i, rfl⟩
          refine ⟨emb i, hN (Set.mem_range_self i), rfl⟩
        have hxN : (x : W) ∈ Submodule.map V₁.subtype N := hle hx1
        rw [Submodule.mem_map] at hxN
        rcases hxN with ⟨y, hyN, hy⟩
        have hyx : y = x := (Submodule.injective_subtype V₁) hy
        simpa [hyx] using hyN
      · exact Submodule.span_le.mpr (by intro w hw; simp)
    rw [htop]
    exact spanFinrank_le_card emb
  let q : Polynomial (Polynomial K) := X ^ (j - d) * p
  have hq_monic : q.Monic := by
    dsimp [q]
    exact (Polynomial.monic_X_pow (j - d)).mul hp_monic
  have hp_ne : p ≠ 0 := hp_monic.ne_zero
  have hq_deg : q.natDegree = j := by
    dsimp [q]
    rw [Polynomial.natDegree_mul]
    · rw [Polynomial.natDegree_X_pow]
      omega
    · exact pow_ne_zero _ Polynomial.X_ne_zero
    · exact hp_ne
  have hq_aeval : Polynomial.aeval T₁ q = 0 := by
    dsimp [q]
    rw [map_mul, map_pow, Polynomial.aeval_X, hp_aeval]
    simp
  have hmon : q = (X ^ j) + ∑ m ∈ Finset.range j, Polynomial.C (q.coeff m) * X ^ m := by
    have hcoeff : q.coeff j = 1 := by
      rw [← hq_deg]
      exact hq_monic.leadingCoeff
    calc
      q = ∑ m ∈ Finset.range (j + 1), Polynomial.C (q.coeff m) * X ^ m := by
        simpa [hq_deg] using q.as_sum_range_C_mul_X_pow
      _ = (∑ m ∈ Finset.range j, Polynomial.C (q.coeff m) * X ^ m) + Polynomial.C (q.coeff j) * X ^ j := by
        rw [Finset.sum_range_succ]
      _ = (∑ m ∈ Finset.range j, Polynomial.C (q.coeff m) * X ^ m) + X ^ j := by
        rw [hcoeff, Polynomial.C_1, one_mul]
      _ = (X ^ j) + ∑ m ∈ Finset.range j, Polynomial.C (q.coeff m) * X ^ m := by
        abel
  have hrel : ∀ x : ↥V₁, (T₁ ^ j) x = ∑ m : Fin j, (-q.coeff m.val) • ((T₁ ^ m.val) x) := by
    intro x
    have h' : (T₁ ^ j) + ∑ m ∈ Finset.range j, (q.coeff m) • (T₁ ^ m) = 0 := by
      calc
        (T₁ ^ j) + ∑ m ∈ Finset.range j, (q.coeff m) • (T₁ ^ m)
            = Polynomial.aeval T₁ ((X ^ j) + ∑ m ∈ Finset.range j, Polynomial.C (q.coeff m) * X ^ m) := by
              rw [map_add]
              congr 2
              · rw [map_pow, Polynomial.aeval_X]
              · rw [map_sum]
                apply Finset.sum_congr rfl
                intro k hk
                rw [map_mul, map_pow, Polynomial.aeval_X, Polynomial.aeval_C, ← Algebra.smul_def]
        _ = Polynomial.aeval T₁ q := by rw [← hmon]
        _ = 0 := hq_aeval
    have h0 : (T₁ ^ j) x + ∑ m ∈ Finset.range j, (q.coeff m) • ((T₁ ^ m) x) = 0 := by
      simpa [Finset.sum_apply, LinearMap.add_apply, LinearMap.smul_apply] using (LinearMap.congr_fun h' x)
    have h1 : (T₁ ^ j) x = ∑ m ∈ Finset.range j, (-q.coeff m) • ((T₁ ^ m) x) := by
      have : (T₁ ^ j) x = -(∑ m ∈ Finset.range j, (q.coeff m) • ((T₁ ^ m) x)) :=
        eq_neg_of_add_eq_zero_left h0
      have hneg : -(∑ m ∈ Finset.range j, (q.coeff m) • ((T₁ ^ m) x)) =
          ∑ m ∈ Finset.range j, (-q.coeff m) • ((T₁ ^ m) x) := by
        rw [← Finset.sum_neg_distrib]
        apply Finset.sum_congr rfl
        intro k hk
        exact (neg_smul (q.coeff k) ((T₁ ^ k) x)).symm
      exact this.trans hneg
    have hconv : (∑ m ∈ Finset.range j, (-q.coeff m) • ((T₁ ^ m) x)) =
        ∑ m : Fin j, (-q.coeff m.val) • ((T₁ ^ m.val) x) := by
      rw [Finset.sum_fin_eq_sum_range]
      apply Finset.sum_congr rfl
      intro k hk
      rw [dif_pos (Finset.mem_range.mp hk)]
    exact h1.trans hconv
  refine ⟨fun m : Fin j => -q.coeff m.val, ?_⟩
  intro w hw
  let x : ↥V₁ := ⟨w, hw⟩
  have hx := hrel x
  have hrest : ∀ n (y : ↥V₁), ((T₁ ^ n) y : W) = (T ^ n) (y : W) := by
    intro n y
    induction n generalizing y with
    | zero => rfl
    | succ n ih =>
        rw [pow_succ, Module.End.mul_apply, ih (T₁ y)]
        change (T ^ n) (T (y : W)) = (T ^ (n + 1)) (y : W)
        rw [pow_succ', Module.End.mul_apply]
        simpa [Module.End.mul_apply] using
          (congrArg (fun f : Module.End (Polynomial K) W => f (y : W))
            ((Commute.refl T).pow_right n |>.eq)).symm
  have hpush : (↑(∑ m : Fin j, (-q.coeff m.val) • ((T₁ ^ m.val) x)) : W) =
      ∑ m : Fin j, (-q.coeff m.val) • (((T₁ ^ m.val) x) : W) := by
    rw [Submodule.coe_sum]
    apply Finset.sum_congr rfl
    intro k hk
    rw [Submodule.coe_smul_of_tower]
  calc
    (T ^ j) w = ((T₁ ^ j) x : W) := by
      rw [hrest j x]
    _ = ∑ m : Fin j, (-q.coeff m.val) • ((T ^ m.val) w) := by
      have h0 : ((T₁ ^ j) x : W) = ∑ m : Fin j, (-q.coeff m.val) • (((T₁ ^ m.val) x) : W) :=
        (congrArg (fun z : ↥V₁ => (z : W)) hx).trans hpush
      rw [h0]
      apply Finset.sum_congr rfl
      intro m hm
      rw [hrest m.val x]

lemma finrank_le_sum {K : Type*} [Field K] {W : Type u} [AddCommGroup W]
    [Module (Polynomial K) W] [Module K W] [IsScalarTower K (Polynomial K) W]
    [FiniteDimensional K W]
    {r : ℕ} (A : Module.End K W) (B : Module.End K W) (Bₓ : Module.End (Polynomial K) W)
    (hAB : Commute A B)
    (hB : Bₓ.restrictScalars (R := K) = B)
    (hA : ∀ w : W, A w = (Polynomial.X : Polynomial K) • w)
    (v : Fin r → W) (k : Fin r → ℕ)
    (hk_anti : Antitone k)
    (hann : ∀ i, (Polynomial.X ^ k i : Polynomial K) • v i = 0)
    (hIndep : iSupIndep (fun i : Fin r => Submodule.span (Polynomial K) ({v i} : Set W)))
    (hSup : ⨆ i : Fin r, Submodule.span (Polynomial K) ({v i} : Set W) = ⊤) :
    Module.finrank K (Algebra.adjoin K ({A, B} : Set (Module.End K W))) ≤ ∑ i : Fin r, k i := by
  classical
  let G : Fin r → Submodule (Polynomial K) W := fun i => Submodule.span (Polynomial K) ({v i} : Set W)
  let F : ℕ → Submodule K (Module.End K W) :=
    fun j => Submodule.span K {T : Module.End K W | ∃ (a : ℕ) (m : Fin r), (m : ℕ) < j ∧ T = A ^ a * B ^ (m : ℕ)}
  let V₁ : Fin r → Submodule (Polynomial K) W := fun j => ⨆ i ∈ {i : Fin r | i < j}, G i
  let V₂ : Fin r → Submodule (Polynomial K) W := fun j => ⨆ i ∈ {i : Fin r | j ≤ i}, G i
  have hIsCompl : ∀ j : Fin r, IsCompl (V₁ j) (V₂ j) := by
    intro j
    exact isCompl_split G j hIndep hSup
  let π₁ : Fin r → Module.End (Polynomial K) W :=
    fun j => LinearMap.ofIsCompl (hIsCompl j) (V₁ j).subtype 0
  let π₂ : Fin r → Module.End (Polynomial K) W := fun j => 1 - π₁ j
  have hApow : ∀ j (w : W), (A ^ (k j)) w = (Polynomial.X ^ (k j) : Polynomial K) • w := by
    intro j w
    induction (k j) generalizing w with
    | zero => simp [hA]
    | succ n ih =>
        rw [pow_succ, Module.End.mul_apply, ih, hA]
        simpa [pow_succ, mul_comm, ← mul_smul]
  have hkillGen : ∀ j i, j ≤ i → (A ^ (k j)) (v i) = 0 := by
    intro j i hji
    rw [hApow]
    have hki : k i ≤ k j := hk_anti hji
    calc
      (Polynomial.X ^ (k j) : Polynomial K) • v i
          = (Polynomial.X ^ (k j - k i) : Polynomial K) • ((Polynomial.X ^ (k i) : Polynomial K) • v i) := by
            rw [← mul_smul, ← pow_add, Nat.sub_add_cancel hki]
      _ = 0 := by rw [hann i]; simp
  let Aₓpow : Fin r → Module.End (Polynomial K) W := fun j =>
    { toFun := fun w => (Polynomial.X ^ (k j) : Polynomial K) • w
      map_add' := by intro x y; simp [smul_add]
      map_smul' := by
        intro r x
        rw [← mul_smul, mul_comm, mul_smul]
        rfl }
  have hApowₓ : ∀ j, (Aₓpow j : W →ₗ[K] W) = A ^ (k j) := by
    intro j
    ext w
    rw [hApow j w]
    rfl
  have hkillV₂ : ∀ j w, w ∈ (V₂ j : Submodule (Polynomial K) W) → (A ^ (k j)) w = 0 := by
    intro j w hw
    have hker : V₂ j ≤ (Aₓpow j).ker := by
      rw [iSup₂_le_iff]
      intro i hi
      change Submodule.span (Polynomial K) ({v i} : Set W) ≤ (Aₓpow j).ker
      rw [Submodule.span_le]
      rintro x hx
      change x ∈ (Aₓpow j).ker
      rw [LinearMap.mem_ker]
      rcases hx with rfl
      change (Polynomial.X ^ (k j) : Polynomial K) • v i = 0
      simpa [hApow j (v i)] using hkillGen j i hi
    have hwker : w ∈ (Aₓpow j).ker := hker hw
    rw [LinearMap.mem_ker] at hwker
    rw [← hApowₓ j]
    exact hwker
  have hπ₂mem : ∀ j w, (π₂ j : W →ₗ[K] W) w ∈ (V₂ j : Submodule (Polynomial K) W) := by
    intro j w
    exact ofIsCompl_range_subset (hIsCompl j) w
  have hV₂kill : ∀ j : Fin r, A ^ (k j) * (π₂ j : W →ₗ[K] W) = 0 := by
    intro j
    ext w
    exact hkillV₂ j ((π₂ j : W →ₗ[K] W) w) (hπ₂mem j w)
  have hAcommπ₁ : ∀ j : Fin r, Commute A (π₁ j : W →ₗ[K] W) := by
    intro j
    ext w
    calc
      A ((π₁ j : W →ₗ[K] W) w) = (Polynomial.X : Polynomial K) • ((π₁ j : W →ₗ[Polynomial K] W) w) := by
        rw [hA]; rfl
      _ = (π₁ j : W →ₗ[Polynomial K] W) ((Polynomial.X : Polynomial K) • w) := by
        rw [← map_smul (π₁ j : W →ₗ[Polynomial K] W)]
      _ = (π₁ j : W →ₗ[K] W) (A w) := by
        rw [hA]; rfl
  let B₁ : Fin r → Module.End K W := fun j =>
    (π₁ j : W →ₗ[K] W) * B * (π₁ j : W →ₗ[K] W)
  let B₁ₓ : Fin r → Module.End (Polynomial K) W := fun j => π₁ j * Bₓ * π₁ j
  have hB₁ : ∀ j, (B₁ₓ j : W →ₗ[K] W) = B₁ j := by
    intro j
    ext w
    change (π₁ j * Bₓ * π₁ j) w = ((π₁ j : W →ₗ[K] W) * B * (π₁ j : W →ₗ[K] W)) w
    simp only [Module.End.mul_apply]
    rw [← hB]
    rfl
  have hCanc : ∀ j, A ^ (k j) * (B - B₁ j) = 0 := by
    intro j
    have hident : B - B₁ j = (π₂ j : W →ₗ[K] W) * B * (π₁ j : W →ₗ[K] W) + B * (π₂ j : W →ₗ[K] W) := by
      dsimp [B₁, π₂]
      ext w
      simp [Module.End.mul_apply, LinearMap.sub_apply, LinearMap.add_apply, map_sub]
    have ht1 : A ^ (k j) * ((π₂ j : W →ₗ[K] W) * B * (π₁ j : W →ₗ[K] W)) = 0 := by
      rw [← mul_assoc, ← mul_assoc, hV₂kill j]
      simp
    have hABk : Commute (A ^ (k j)) B := by
      simpa using hAB.pow_pow (k j) 1
    have ht2 : A ^ (k j) * (B * (π₂ j : W →ₗ[K] W)) = 0 := by
      rw [← mul_assoc, hABk.eq, mul_assoc, hV₂kill j]
      simp
    rw [hident, mul_add, ht1, ht2]
    simp
  have hTel : ∀ j : Fin r, B ^ j.val - B₁ j ^ j.val =
      ∑ l : Fin j.val, B ^ (j.val - 1 - l.val) * (B - B₁ j) * B₁ j ^ l.val := by
    intro j
    exact pow_sub_sum B (B₁ j) j.val
  have hAnnPows' : ∀ j m, A ^ (k j) * (B ^ m - B₁ j ^ m) = 0 := by
    intro j m
    rw [pow_sub_sum B (B₁ j) m, Finset.mul_sum]
    apply Finset.sum_eq_zero
    intro l hl
    have hc : Commute (A ^ (k j)) (B ^ (m - 1 - l.val)) := hAB.pow_pow _ _
    have hstep : A ^ (k j) * (B ^ (m - 1 - l.val) * (B - B₁ j) * B₁ j ^ l.val) = 0 := by
      calc
        A ^ (k j) * (B ^ (m - 1 - l.val) * (B - B₁ j) * B₁ j ^ l.val)
            = A ^ (k j) * (B ^ (m - 1 - l.val) * ((B - B₁ j) * B₁ j ^ l.val)) := by
              rw [mul_assoc]
        _ = (A ^ (k j) * B ^ (m - 1 - l.val)) * ((B - B₁ j) * B₁ j ^ l.val) := by
              rw [← mul_assoc]
        _ = (B ^ (m - 1 - l.val) * A ^ (k j)) * ((B - B₁ j) * B₁ j ^ l.val) := by
              rw [hc.eq]
        _ = B ^ (m - 1 - l.val) * (A ^ (k j) * ((B - B₁ j) * B₁ j ^ l.val)) := by
              rw [mul_assoc]
        _ = B ^ (m - 1 - l.val) * ((A ^ (k j) * (B - B₁ j)) * B₁ j ^ l.val) := by
              rw [show A ^ (k j) * ((B - B₁ j) * B₁ j ^ l.val) = (A ^ (k j) * (B - B₁ j)) * B₁ j ^ l.val from by rw [← mul_assoc]]
        _ = B ^ (m - 1 - l.val) * (0 * B₁ j ^ l.val) := by
              rw [hCanc j]
        _ = 0 := by simp
    exact hstep
  have hAnnPows : ∀ j : Fin r, A ^ (k j) * (B ^ j.val - B₁ j ^ j.val) = 0 := fun j => hAnnPows' j j.val
  have hπ₁mem : ∀ j w, (π₁ j : W →ₗ[K] W) w ∈ (V₁ j : Submodule (Polynomial K) W) := by
    intro j w
    change (π₁ j : W →ₗ[Polynomial K] W) w ∈ (V₁ j : Submodule (Polynomial K) W)
    dsimp [π₁]
    rw [LinearMap.ofIsCompl_eq_add (hIsCompl j)]
    simp
  have hAπ₁ : ∀ j, A ^ (k j) * (π₁ j : W →ₗ[K] W) = A ^ (k j) := by
    intro j
    have hπ₁ : (π₁ j : W →ₗ[K] W) = 1 - (π₂ j : W →ₗ[K] W) := by
      dsimp [π₂]
      ext w
      simp
    rw [hπ₁, mul_sub, hV₂kill j, sub_zero, mul_one]
  have hπ₁idem : ∀ j, (π₁ j : W →ₗ[K] W) * (π₁ j : W →ₗ[K] W) = (π₁ j : W →ₗ[K] W) := by
    intro j
    ext w
    rw [Module.End.mul_apply]
    have hmem : (π₁ j : W →ₗ[K] W) w ∈ (V₁ j : Submodule (Polynomial K) W) := hπ₁mem j w
    have hsub : ∀ v : W, v ∈ (V₁ j : Submodule (Polynomial K) W) →
        (π₁ j : W →ₗ[K] W) v = v := by
      intro v hv
      change (π₁ j : W →ₗ[Polynomial K] W) v = v
      dsimp [π₁]
      exact LinearMap.ofIsCompl_apply_left (hIsCompl j) ⟨v, hv⟩
    exact hsub ((π₁ j : W →ₗ[K] W) w) hmem
  have hB₁π₁_base : ∀ j, B₁ j * (π₁ j : W →ₗ[K] W) = B₁ j := by
    intro j
    dsimp [B₁]
    rw [mul_assoc, hπ₁idem j]
  have hB₁π₁ : ∀ j m, 1 ≤ m → (B₁ j) ^ m * (π₁ j : W →ₗ[K] W) = (B₁ j) ^ m := by
    intro j m hm
    induction m with
    | zero => omega
    | succ m ih =>
        rw [pow_succ']
        by_cases h0 : m = 0
        · rw [h0]
          simp [pow_zero, one_mul, hB₁π₁_base j, pow_one]
        · rw [mul_assoc, ih (by omega)]
  have hB₁pow' : ∀ j n (w : W), (B₁ₓ j ^ n) w = (B₁ j ^ n) w := by
    intro j n w
    induction n with
    | zero => simp
    | succ n ih =>
        rw [pow_succ', Module.End.mul_apply, ih]
        conv => rhs; rw [pow_succ', Module.End.mul_apply]
        rw [← congrArg (fun f : Module.End K W => f ((B₁ j ^ n) w)) (hB₁ j)]
        rfl
  have hB₁pow : ∀ j n, (B₁ₓ j ^ n : W →ₗ[K] W) = B₁ j ^ n := by
    intro j n
    induction n with
    | zero => ext w; simp [B₁ₓ, B₁]
    | succ n ih =>
        ext w
        simp [pow_succ', Module.End.mul_apply, hB₁ j, ih]
  have hApowX : ∀ n (z : W), (A ^ n) z = (Polynomial.X ^ n : Polynomial K) • z := by
    intro n z
    induction n generalizing z with
    | zero => simp [hA]
    | succ n ih =>
        rw [pow_succ, Module.End.mul_apply, ih, hA]
        rw [← mul_smul]
        congr 1
  have hsmul : ∀ (c : Polynomial K) (z : W), c • z = (Polynomial.aeval A c) z := by
    intro c z
    calc
      c • z = (∑ m ∈ Finset.range (c.natDegree + 1), (c.coeff m) • ((Polynomial.X ^ m : Polynomial K) • z)) := by
        conv => lhs; rw [c.as_sum_range_C_mul_X_pow]
        rw [Finset.sum_smul]
        apply Finset.sum_congr rfl
        intro m hm
        rw [← smul_smul]
        exact algebraMap_smul (R := K) (A := Polynomial K) (c.coeff m) ((Polynomial.X ^ m : Polynomial K) • z)
      _ = ∑ m ∈ Finset.range (c.natDegree + 1), (c.coeff m) • ((A ^ m) z) := by
        apply Finset.sum_congr rfl
        intro m hm
        rw [hApowX m z]
      _ = (∑ m ∈ Finset.range (c.natDegree + 1), (c.coeff m) • (A ^ m)) z := by
        simp [Finset.sum_apply, LinearMap.smul_apply]
      _ = (Polynomial.aeval A c) z := by
        rw [← Polynomial.aeval_eq_sum_range]
  have hAB₁ : ∀ j m, A ^ (k j) * B ^ m = A ^ (k j) * (B₁ j) ^ m * (π₁ j : W →ₗ[K] W) := by
    intro j m
    have hann : A ^ (k j) * B ^ m = A ^ (k j) * (B₁ j) ^ m := by
      exact sub_eq_zero.mp (by
        rw [← mul_sub]
        exact hAnnPows' j m)
    rw [hann]
    by_cases hm : m = 0
    · rw [hm]
      simp [pow_zero, mul_one]
      rw [hAπ₁ j]
    · calc
        A ^ (k j) * B₁ j ^ m = A ^ (k j) * (B₁ j ^ m * (π₁ j : W →ₗ[K] W)) := by
          conv => lhs; rw [← hB₁π₁ j m (by omega)]
        _ = A ^ (k j) * B₁ j ^ m * (π₁ j : W →ₗ[K] W) := by
          rw [← mul_assoc]
  have hRow : ∀ j : Fin r, A ^ (k j) * B ^ j.val ∈ F j.val := by
    intro j
    let gens : Fin j.val → W := fun i => v ⟨i.val, lt_trans i.2 j.2⟩
    have hgen : V₁ j = Submodule.span (Polynomial K) (Set.range gens) := by
      apply le_antisymm
      · rw [iSup₂_le_iff]
        intro i hi
        change Submodule.span (Polynomial K) ({v i} : Set W) ≤ Submodule.span (Polynomial K) (Set.range gens)
        rw [Submodule.span_le]
        rintro w hw
        rcases hw with rfl
        exact Submodule.subset_span ⟨⟨i.val, hi⟩, rfl⟩
      · rw [Submodule.span_le]
        rintro w ⟨i, rfl⟩
        change v ⟨i.val, lt_trans i.2 j.2⟩ ∈ (V₁ j : Submodule (Polynomial K) W)
        exact le_iSup₂ (f := fun a ha => G a) ⟨i.val, lt_trans i.2 j.2⟩ i.2
          (Submodule.subset_span (by simp))
    have hT : ∀ w ∈ V₁ j, B₁ₓ j w ∈ V₁ j := by
      intro w hw
      simpa [B₁ₓ, Module.End.mul_apply] using hπ₁mem j (Bₓ (π₁ j w))
    rcases leading_L1 (T := B₁ₓ j) (V₁ := V₁ j) hT gens hgen with ⟨c, hc⟩
    have hcK : ∀ w ∈ (V₁ j : Submodule (Polynomial K) W), (B₁ j ^ j.val) w =
        ∑ m : Fin j.val, (c m) • ((B₁ j ^ m.val) w) := by
      intro w hw
      have hx := hc w hw
      calc
        (B₁ j ^ j.val) w = (B₁ₓ j ^ j.val) w := by rw [hB₁pow' j j.val]
        _ = ∑ m : Fin j.val, (c m) • ((B₁ₓ j ^ m.val) w) := hx
        _ = ∑ m : Fin j.val, (c m) • ((B₁ j ^ m.val) w) := by
          apply Finset.sum_congr rfl
          intro m hm
          rw [hB₁pow' j m.val]
    have hAXlin : ∀ j (c : Polynomial K) z, (A ^ (k j)) (c • z) = c • ((A ^ (k j)) z) := by
      intro j c z
      rw [hApow j, hApow j]
      calc
        (Polynomial.X ^ (k j)) • (c • z) = (Polynomial.X ^ (k j) * c) • z := by rw [smul_smul]
        _ = (c * Polynomial.X ^ (k j)) • z := by rw [mul_comm]
        _ = c • ((Polynomial.X ^ (k j)) • z) := by rw [← smul_smul]
    have hident : A ^ (k j) * B ^ j.val =
        ∑ m : Fin j.val, (Polynomial.aeval A (c m)) * A ^ (k j) * B ^ m.val := by
      ext w
      calc
        (A ^ (k j) * B ^ j.val) w = (A ^ (k j)) ((B₁ j ^ j.val) ((π₁ j : W →ₗ[K] W) w)) := by
          have h := LinearMap.congr_fun (hAB₁ j j.val) w
          simpa [Module.End.mul_apply] using h
        _ = (A ^ (k j)) (∑ m : Fin j.val, (c m) • ((B₁ j ^ m.val) ((π₁ j : W →ₗ[K] W) w))) := by
          rw [hcK ((π₁ j : W →ₗ[K] W) w) (hπ₁mem j w)]
        _ = ∑ m : Fin j.val, (c m) • ((A ^ (k j)) ((B₁ j ^ m.val) ((π₁ j : W →ₗ[K] W) w))) := by
          rw [map_sum]
          apply Finset.sum_congr rfl
          intro m hm
          rw [← hAXlin j (c m)]
        _ = ∑ m : Fin j.val, (Polynomial.aeval A (c m)) ((A ^ (k j)) ((B₁ j ^ m.val) ((π₁ j : W →ₗ[K] W) w))) := by
          apply Finset.sum_congr rfl
          intro m hm
          rw [hsmul (c m)]
        _ = ∑ m : Fin j.val, (Polynomial.aeval A (c m)) ((A ^ (k j)) ((B ^ m.val) w)) := by
          apply Finset.sum_congr rfl
          intro m hm
          by_cases hm0 : m.val = 0
          · rw [hm0, pow_zero]
            simp
            have hπ₁w : (A ^ (k j)) ((π₁ j : W →ₗ[K] W) w) = (A ^ (k j)) w := by
              simpa [Module.End.mul_apply] using congrArg (fun f : Module.End K W => f w) (hAπ₁ j)
            exact congrArg (fun z : W => (Polynomial.aeval A (c m)) z) hπ₁w
          · have hB₁π₁' : (B₁ j ^ m.val) * (π₁ j : W →ₗ[K] W) = B₁ j ^ m.val := hB₁π₁ j m.val (by omega)
            have h1 : (B₁ j ^ m.val) ((π₁ j : W →ₗ[K] W) w) = (B₁ j ^ m.val) w := by
              simpa [Module.End.mul_apply] using LinearMap.congr_fun hB₁π₁' w
            rw [h1]
            have hred : A ^ (k j) * B ^ m.val = A ^ (k j) * (B₁ j ^ m.val) := by
              exact sub_eq_zero.mp (by
                rw [← mul_sub]
                exact hAnnPows' j m.val)
            have hw : (A ^ (k j)) ((B₁ j ^ m.val) w) = (A ^ (k j)) ((B ^ m.val) w) := by
              have h' := LinearMap.congr_fun hred w
              simpa [Module.End.mul_apply] using h'.symm
            exact congrArg (fun z : W => (Polynomial.aeval A (c m)) z) hw
        _ = (∑ m : Fin j.val, (Polynomial.aeval A (c m)) * A ^ (k j) * B ^ m.val) w := by
          simp [Finset.sum_apply, Module.End.mul_apply, LinearMap.smul_apply]
    have hterms : ∀ m : Fin j.val, (Polynomial.aeval A (c m)) * A ^ (k j) * B ^ m.val ∈ F j.val := by
      intro m
      have hgen' : ∀ t : ℕ, A ^ (t + k j) * B ^ m.val ∈ F j.val := by
        intro t
        dsimp [F]
        apply Submodule.subset_span
        exact ⟨t + k j, ⟨m.val, lt_trans m.2 j.2⟩, m.2, rfl⟩
      have hpow : (Polynomial.aeval A (c m)) = ∑ t ∈ Finset.range ((c m).natDegree + 1), (c m).coeff t • (A ^ t) := by
        rw [Polynomial.aeval_eq_sum_range]
      rw [hpow, Finset.sum_mul, Finset.sum_mul]
      apply Submodule.sum_mem
      intro t ht
      rw [smul_mul_assoc, smul_mul_assoc, ← pow_add]
      exact Submodule.smul_mem (F j.val) ((c m).coeff t) (hgen' t)
    rw [hident]
    apply Submodule.sum_mem
    intro m hm
    exact hterms m
  have hBpow : ∀ n (w : W), (Bₓ ^ n) w = (B ^ n) w := by
    intro n w
    induction n with
    | zero => simp
    | succ n ih =>
        rw [pow_succ', Module.End.mul_apply, ih]
        conv => rhs; rw [pow_succ', Module.End.mul_apply]
        rw [← congrArg (fun f : Module.End K W => f ((B ^ n) w)) (hB)]
        rfl
  have hL1global : B ^ r ∈ F r := by
    have hgen : (⊤ : Submodule (Polynomial K) W) = Submodule.span (Polynomial K) (Set.range v) := by
      apply le_antisymm
      · rw [← hSup]
        exact iSup_le (fun i => by
          change G i ≤ Submodule.span (Polynomial K) (Set.range v)
          rw [Submodule.span_le]
          intro w hw
          rcases hw with rfl
          exact Submodule.subset_span ⟨i, rfl⟩)
      · intro w hw
        simp
    rcases leading_L1 (T := Bₓ) (V₁ := ⊤) (by intro w hw; simp) v hgen with ⟨c, hc⟩
    have hcK : ∀ w, (B ^ r) w = ∑ m : Fin r, (c m) • ((B ^ m.val) w) := by
      intro w
      have hx := hc w (by simp)
      calc
        (B ^ r) w = (Bₓ ^ r) w := by rw [hBpow r w]
        _ = ∑ m : Fin r, (c m) • ((Bₓ ^ m.val) w) := hx
        _ = ∑ m : Fin r, (c m) • ((B ^ m.val) w) := by
          apply Finset.sum_congr rfl
          intro m hm
          rw [hBpow m.val w]
    have hident : B ^ r = ∑ m : Fin r, (Polynomial.aeval A (c m)) * B ^ m.val := by
      ext w
      calc
        (B ^ r) w = ∑ m : Fin r, (c m) • ((B ^ m.val) w) := hcK w
        _ = ∑ m : Fin r, (Polynomial.aeval A (c m)) ((B ^ m.val) w) := by
          apply Finset.sum_congr rfl
          intro m hm
          rw [hsmul (c m)]
        _ = (∑ m : Fin r, (Polynomial.aeval A (c m)) * B ^ m.val) w := by
          simp [Finset.sum_apply, Module.End.mul_apply, LinearMap.smul_apply]
    have hterms : ∀ m : Fin r, (Polynomial.aeval A (c m)) * B ^ m.val ∈ F r := by
      intro m
      have hgen' : ∀ t : ℕ, A ^ t * B ^ m.val ∈ F r := by
        intro t
        dsimp [F]
        apply Submodule.subset_span
        exact ⟨t, ⟨m.val, m.2⟩, m.2, rfl⟩
      have hpow : (Polynomial.aeval A (c m)) = ∑ t ∈ Finset.range ((c m).natDegree + 1), (c m).coeff t • (A ^ t) := by
        rw [Polynomial.aeval_eq_sum_range]
      rw [hpow, Finset.sum_mul]
      apply Submodule.sum_mem
      intro t ht
      rw [smul_mul_assoc]
      exact Submodule.smul_mem (F r) ((c m).coeff t) (hgen' t)
    rw [hident]
    apply Submodule.sum_mem
    intro m hm
    exact hterms m
  let S₁ : (Σ m : Fin r, Fin (k m)) → Module.End K W := fun ⟨m, a⟩ => A ^ a.val * B ^ m.val
  have hhelper : ∀ (a b j : ℕ) (T : Module.End K W),
      T ∈ F j →
      A ^ a * B ^ b * T ∈ Submodule.span K {T' : Module.End K W | ∃ t m', m' < j ∧ T' = A ^ t * B ^ (b + m')} := by
    intro a b j T hT
    refine Submodule.span_induction
      (p := fun U _ => A ^ a * B ^ b * U ∈
        Submodule.span K {T' : Module.End K W | ∃ t m', m' < j ∧ T' = A ^ t * B ^ (b + m')})
      ?_ ?_ ?_ ?_ hT
    · rintro T' hT'
      rcases hT' with ⟨a', m', hlt, rfl⟩
      apply Submodule.subset_span
      refine ⟨a + a', m', hlt, ?_⟩
      have hc : Commute (A ^ a') (B ^ b) := hAB.pow_pow _ _
      rw [pow_add, pow_add]
      change A ^ a * ((B ^ b * A ^ a') * B ^ (m' : ℕ)) = (A ^ a * A ^ a') * (B ^ b * B ^ (m' : ℕ))
      rw [← hc.eq]
      rfl
    · rw [mul_zero]
      exact Submodule.zero_mem _
    · intro x y hx hy px py
      simpa [mul_add] using add_mem px py
    · intro c x hx px
      simpa [map_smul] using Submodule.smul_mem _ c px
  have hmono : ∀ (a m : ℕ), A ^ a * B ^ m ∈ Submodule.span K (Set.range S₁) := by
    have h : ∀ m, ∀ a, A ^ a * B ^ m ∈ Submodule.span K (Set.range S₁) := by
      intro m
      induction m using Nat.strong_induction_on with
      | h m ih =>
          intro a
          by_cases hm : m < r
          · let j : Fin r := ⟨m, hm⟩
            by_cases ha : a < k j
            · exact Submodule.subset_span ⟨⟨j, ⟨a, ha⟩⟩, rfl⟩
            · have hk : a - k j + k j = a := by omega
              have hrew : A ^ a * B ^ m = A ^ (a - k j) * (A ^ (k j) * B ^ m) := by
                calc
                  A ^ a * B ^ m = (A ^ (a - k j) * A ^ (k j)) * B ^ m := by
                    conv => lhs; rw [← hk, pow_add]
                  _ = A ^ (a - k j) * (A ^ (k j) * B ^ m) := by
                    rw [mul_assoc]
              have hrow := hRow j
              have hh := hhelper (a - k j) 0 j.val (A ^ (k j) * B ^ m) hrow
              rw [hrew]
              have hle : Submodule.span K {T' : Module.End K W | ∃ t m', m' < j.val ∧ T' = A ^ t * B ^ (0 + m')} ≤
                  Submodule.span K (Set.range S₁) := by
                rw [Submodule.span_le]
                rintro T' ⟨t, m', hlt, rfl⟩
                have hb : m' < m := by
                  dsimp [j] at hlt
                  omega
                simpa using ih m' hb t
              exact hle (by
                simpa [pow_zero, mul_one] using hh)
          · have hle0 : r ≤ m := by omega
            have hmr : m - r + r = m := Nat.sub_add_cancel hle0
            have hrew : A ^ a * B ^ m = A ^ a * B ^ (m - r) * B ^ r := by
              calc
                A ^ a * B ^ m = A ^ a * (B ^ (m - r) * B ^ r) := by
                  conv => lhs; rw [← hmr, pow_add]
                _ = A ^ a * B ^ (m - r) * B ^ r := by rw [← mul_assoc]
            have hh := hhelper a (m - r) r (B ^ r) hL1global
            rw [hrew]
            have hle : Submodule.span K {T' : Module.End K W | ∃ t m', m' < r ∧ T' = A ^ t * B ^ ((m - r) + m')} ≤
                Submodule.span K (Set.range S₁) := by
              rw [Submodule.span_le]
              rintro T' ⟨t, m', hlt, rfl⟩
              have hb : (m - r) + m' < m := by omega
              exact ih ((m - r) + m') hb t
            exact hle hh
    exact fun a m => h m a
  have hmonom : ∀ T : Module.End K W, T ∈ Submonoid.closure ({A, B} : Set (Module.End K W)) →
      ∃ a m, T = A ^ a * B ^ m := by
    intro T hT
    induction hT using Submonoid.closure_induction with
    | one => exact ⟨0, 0, by simp⟩
    | mul x hx y hy ihx ihy =>
        rcases ihx with ⟨a₁, m₁, rfl⟩
        rcases ihy with ⟨a₂, m₂, rfl⟩
        have hc : Commute (A ^ a₂) (B ^ m₁) := hAB.pow_pow _ _
        refine ⟨a₁ + a₂, m₁ + m₂, ?_⟩
        calc
          (A ^ a₁ * B ^ m₁) * (A ^ a₂ * B ^ m₂) = A ^ a₁ * (B ^ m₁ * A ^ a₂) * B ^ m₂ := rfl
          _ = A ^ a₁ * (A ^ a₂ * B ^ m₁) * B ^ m₂ := by rw [hc.eq]
          _ = (A ^ a₁ * A ^ a₂) * (B ^ m₁ * B ^ m₂) := rfl
          _ = A ^ (a₁ + a₂) * B ^ (m₁ + m₂) := by
            rw [← pow_add, ← pow_add]
    | mem x hx =>
        rcases hx with rfl | rfl
        · exact ⟨1, 0, by simp⟩
        · exact ⟨0, 1, by simp⟩
  have hmono' : ∀ T : Module.End K W, T ∈ Submonoid.closure ({A, B} : Set (Module.End K W)) →
      T ∈ Submodule.span K (Set.range S₁) := by
    intro T hT
    rcases hmonom T hT with ⟨a, m, rfl⟩
    exact hmono a m
  have hadj : (Algebra.adjoin K ({A, B} : Set (Module.End K W))).toSubmodule ≤
      Submodule.span K (Set.range S₁) := by
    rw [Algebra.adjoin_eq_span]
    rw [Submodule.span_le]
    exact hmono'
  have hfin : Module.finrank K (Submodule.span K (Set.range S₁)) ≤ ∑ i : Fin r, k i := by
    rw [show Module.finrank K (Submodule.span K (Set.range S₁)) = Set.finrank K (Set.range S₁) from rfl]
    simpa [Fintype.card_sigma] using finrank_range_le_card S₁
  exact (Submodule.finrank_mono hadj).trans hfin

noncomputable def conjAlgEquiv {K : Type*} [Field K] {V W : Type u} [AddCommGroup V] [AddCommGroup W]
    [Module K V] [Module K W] (e : V ≃ₗ[K] W) : Module.End K V ≃ₐ[K] Module.End K W :=
  { toEquiv := (e.conj : Module.End K V ≃ₗ[K] Module.End K W).toEquiv
    map_mul' := by
      intro f g
      ext x
      simp [LinearEquiv.conj_apply]
    map_add' := by
      intro f g
      ext x
      simp [LinearEquiv.conj_apply]
    commutes' := by
      intro r
      ext x
      simp [LinearEquiv.conj_apply, map_smul] }
end L2

namespace Core

open TwoBlock
open scoped BigOperators

universe u

variable {K : Type*} [Field K] [IsAlgClosed K] {V : Type u} [AddCommGroup V] [Module K V] [FiniteDimensional K V]

lemma nilpotent_core (A B : Module.End K V) (hAB : Commute A B) (hA : IsNilpotent A) :
    Module.finrank K (Algebra.adjoin K ({A, B} : Set (Module.End K V))) ≤ Module.finrank K V := by
  classical
  -- Step 1: structure theorem on AEval' A over K[X].
  rcases hA with ⟨m, hm⟩
  have htor : Module.IsTorsion (Polynomial K) (Module.AEval' A) := by
    intro x
    refine ⟨⟨Polynomial.X ^ m, ?hmem⟩, ?_⟩
    · exact mem_nonZeroDivisors_iff.mpr ⟨
        (by intro y hy; exact mul_left_cancel₀ (pow_ne_zero m Polynomial.X_ne_zero) (by simpa using hy)),
        (by intro y hy; exact mul_right_cancel₀ (pow_ne_zero m Polynomial.X_ne_zero) (by simpa using hy))⟩
    · rcases (Module.AEval'.of A).surjective x with ⟨v, rfl⟩
      change (Polynomial.X ^ m : Polynomial K) • (Module.AEval'.of A) v = 0
      rw [Module.AEval'.X_pow_smul_of, hm]
      simp
  rcases Module.equiv_directSum_of_isTorsion (R := Polynomial K) (M := Module.AEval' A) htor with
    ⟨ι, hι, p, hp, e, he⟩
  letI := hι
  letI : DecidableEq ι := Classical.decEq ι
  let fac := fun i : ι => (Polynomial K) ⧸ (Polynomial K ∙ p i ^ e i)
  let gen := fun i : ι => (Submodule.Quotient.mk (1 : Polynomial K) : fac i)
  let eiso : Module.AEval' A ≃ₗ[Polynomial K] DirectSum ι fac := Classical.choice he
  let y := fun i : ι => eiso.symm (DirectSum.of (β := fac) i (gen i))
  let v := fun i : ι => (Module.AEval'.of A).symm (y i)
  let k := e
  have hXpow : ∀ x : Module.AEval' A, (Polynomial.X ^ m : Polynomial K) • x = 0 := by
    intro x
    rcases (Module.AEval'.of A).surjective x with ⟨w, rfl⟩
    change (Polynomial.X ^ m : Polynomial K) • (Module.AEval'.of A) w = 0
    rw [Module.AEval'.X_pow_smul_of, hm]
    simp
  have hpX : ∀ i, e i > 0 → Associated (p i) Polynomial.X := by
    intro i hpos
    have hz : (Polynomial.X ^ m : Polynomial K) • y i = 0 := hXpow (y i)
    have hz1 : eiso.symm ((Polynomial.X ^ m : Polynomial K) •
        (DirectSum.of (β := fac) i (gen i))) = 0 := by
      simpa [y, gen] using hz
    have hz2 : (Polynomial.X ^ m : Polynomial K) •
        (DirectSum.of (β := fac) i (gen i)) = 0 := by
      apply eiso.symm.injective
      simpa using hz1
    have hz3 : (Polynomial.X ^ m : Polynomial K) • (gen i) = 0 := by
      apply DirectSum.of_injective (β := fac) i
      rw [← DirectSum.lof_eq_of (Polynomial K) ι fac i (Polynomial.X ^ m • gen i)]
      rw [map_smul (DirectSum.lof (Polynomial K) ι fac i)]
      rw [DirectSum.lof_eq_of (Polynomial K) ι fac i (gen i)]
      simpa using hz2
    have hmk : (Submodule.Quotient.mk (Polynomial.X ^ m : Polynomial K) : fac i) = 0 := by
      dsimp [gen] at hz3
      change (Polynomial.X ^ m : Polynomial K) • (Submodule.Quotient.mk (1 : Polynomial K)) = 0 at hz3
      rw [← Submodule.Quotient.mk_smul] at hz3
      simpa [smul_eq_mul, mul_one] using hz3
    have hdvd : (p i) ^ (e i) ∣ Polynomial.X ^ m := by
      have hmem : Polynomial.X ^ m ∈ (Polynomial K) ∙ p i ^ e i :=
        (Submodule.Quotient.mk_eq_zero _).mp hmk
      exact Ideal.mem_span_singleton.mp (by simpa using hmem)
    have hpdvd : p i ∣ Polynomial.X ^ m := by
      exact dvd_trans (dvd_pow_self (p i) (by omega : e i ≠ 0)) hdvd
    have hpXd : p i ∣ Polynomial.X := (hp i).prime.dvd_of_dvd_pow hpdvd
    exact (hp i).associated_of_dvd Polynomial.irreducible_X hpXd
  have hann : ∀ i, (A ^ e i) (v i) = 0 := by
    intro i
    by_cases h0 : e i = 0
    · have hmk1 : (Submodule.Quotient.mk (1 : Polynomial K) : fac i) = 0 := by
        apply (Submodule.Quotient.mk_eq_zero _).mpr
        simpa [h0] using (Ideal.mem_span_singleton).mpr (dvd_refl (1 : Polynomial K))
      have hof0 : DirectSum.of (β := fac) i (gen i) = 0 := by
        simpa [gen] using congrArg (fun z : fac i => DirectSum.of (β := fac) i z) hmk1
      have hy0 : y i = 0 := by
        dsimp [y]
        simpa [hof0]
      have hv0 : v i = 0 := by
        dsimp [v]
        simpa [hy0]
      rw [h0]
      simpa [hv0]
    · have hpos : 0 < e i := by omega
      have hfac : (p i) ^ (e i) • (gen i) = 0 := by
        dsimp [gen]
        change (p i) ^ (e i) • (Submodule.Quotient.mk (1 : Polynomial K)) = 0
        rw [← Submodule.Quotient.mk_smul]
        rw [smul_eq_mul, mul_one]
        apply (Submodule.Quotient.mk_eq_zero _).mpr
        simpa using (Ideal.mem_span_singleton).mpr (dvd_refl ((p i) ^ (e i)))
      have hfacy : (p i) ^ (e i) • y i = 0 := by
        calc
          (p i) ^ (e i) • y i =
              eiso.symm ((p i) ^ (e i) • (DirectSum.of (β := fac) i (gen i))) := by
            dsimp [y]
            exact (LinearEquiv.map_smul eiso.symm ((p i) ^ (e i)) _).symm
          _ = eiso.symm (DirectSum.of (β := fac) i ((p i) ^ (e i) • (gen i))) := by
            congr 1
            have hcomp : (p i) ^ (e i) • (DirectSum.of (β := fac) i (gen i)) =
                DirectSum.of (β := fac) i ((p i) ^ (e i) • (gen i)) := by
              rw [← DirectSum.lof_eq_of (Polynomial K) ι fac i (gen i)]
              rw [← DirectSum.lof_eq_of (Polynomial K) ι fac i ((p i) ^ (e i) • (gen i))]
              exact (map_smul (DirectSum.lof (Polynomial K) ι fac i)
                ((p i) ^ (e i)) (gen i)).symm
            exact hcomp
          _ = 0 := by
            rw [hfac]
            simp
      have hX : (Polynomial.X ^ (e i) : Polynomial K) • y i = 0 := by
        rcases hpX i hpos with ⟨u, hu⟩
        calc
          (Polynomial.X ^ (e i)) • y i =
              ((u : Polynomial K) ^ (e i) * (p i) ^ (e i)) • y i := by
            congr 1
            rw [← hu, mul_pow]
            ring
          _ = (u : Polynomial K) ^ (e i) • ((p i) ^ (e i) • y i) := by
            exact (smul_smul ((u : Polynomial K) ^ (e i)) ((p i) ^ (e i)) (y i)).symm
          _ = 0 := by rw [hfacy]; simp
      have hof : (Module.AEval'.of A) ((A ^ (e i)) • v i) = 0 := by
        rw [← Module.AEval'.X_pow_smul_of A (v i) (e i)]
        simpa [v, y] using hX
      exact ((Module.End.smul_def (A ^ (e i)) (v i)).symm.trans
        ((Module.AEval'.of A).injective hof))
  have hfin_fac : ∀ i, Module.finrank K (fac i) = e i := by
    intro i
    have hpne : p i ≠ 0 := (hp i).ne_zero
    have hfr : Module.finrank K (fac i) = (p i ^ e i).natDegree := by
      exact (AdjoinRoot.powerBasis (pow_ne_zero (e i) hpne)).finrank
    rw [hfr, Polynomial.natDegree_pow]
    by_cases h0 : e i = 0
    · rw [h0]; simp
    · have hpos : 0 < e i := by omega
      have hp1 : (p i).natDegree = 1 := by
        have hpdX := Associated.dvd (hpX i hpos)
        have hXdp := Associated.dvd' (hpX i hpos)
        have h1 : (p i).natDegree ≤ (Polynomial.X : Polynomial K).natDegree := by
          exact Polynomial.natDegree_le_of_dvd hpdX (Polynomial.X_ne_zero)
        have h2 : (Polynomial.X : Polynomial K).natDegree ≤ (p i).natDegree := by
          exact Polynomial.natDegree_le_of_dvd hXdp hpne
        have hX1 : (Polynomial.X : Polynomial K).natDegree = 1 := Polynomial.natDegree_X
        omega
      rw [hp1]; simp
  have hbasis : ∀ i, Module.Basis (Fin (p i ^ e i).natDegree) K (fac i) := by
    intro i
    exact (AdjoinRoot.powerBasis (pow_ne_zero (e i) (hp i).ne_zero)).basis
  letI : ∀ i, Module.Finite K (fac i) := fun i => Module.Finite.of_basis (hbasis i)
  letI : ∀ i, Module.Free K (fac i) := fun i => Module.Free.of_basis (hbasis i)
  have hfinrank1 : Module.finrank K V = Module.finrank K (Module.AEval' A) := by
    exact LinearEquiv.finrank_eq (Module.AEval'.of A)
  have hfinrank2 : Module.finrank K (Module.AEval' A) = Module.finrank K (DirectSum ι fac) := by
    exact LinearEquiv.finrank_eq (eiso.restrictScalars K)
  have hfinrank3 : Module.finrank K (DirectSum ι fac) = ∑ i, Module.finrank K (fac i) := by
    exact Module.finrank_directSum K fac
  have hsum : Module.finrank K V = ∑ i, e i := by
    calc
      Module.finrank K V = Module.finrank K (Module.AEval' A) := hfinrank1
      _ = Module.finrank K (DirectSum ι fac) := hfinrank2
      _ = ∑ i, Module.finrank K (fac i) := hfinrank3
      _ = ∑ i, e i := by
        apply Finset.sum_congr rfl
        intro i hi
        exact hfin_fac i
  -- Step 2: apply L2.finrank_le_sum on AEval' A.
  let φ : Module.End K V ≃ₐ[K] Module.End K (Module.AEval' A) := L2.conjAlgEquiv (Module.AEval'.of A)
  let A' : Module.End K (Module.AEval' A) := φ A
  let B' : Module.End K (Module.AEval' A) := φ B
  have hA' : ∀ w : Module.AEval' A, A' w = (Polynomial.X : Polynomial K) • w := by
    intro w
    rcases (Module.AEval'.of A).surjective w with ⟨v', rfl⟩
    dsimp [A', φ]
    simp [L2.conjAlgEquiv, LinearEquiv.conj_apply, Module.AEval'.X_smul_of]
  have hA'of1 : ∀ u : V, A' ((Module.AEval'.of A) u) = (Module.AEval'.of A) (A u) := by
    intro u
    dsimp [A', φ]
    simp [L2.conjAlgEquiv, LinearEquiv.conj_apply]
  have hA'of : ∀ m (w : V), (A' ^ m) ((Module.AEval'.of A) w) = (Module.AEval'.of A) ((A ^ m) w) := by
    intro m w
    induction m with
    | zero => simp
    | succ m ih =>
        calc
          (A' ^ (m + 1)) ((Module.AEval'.of A) w) = A' ((A' ^ m) ((Module.AEval'.of A) w)) := by
            rw [pow_succ', Module.End.mul_apply]
          _ = A' ((Module.AEval'.of A) ((A ^ m) w)) := by rw [ih]
          _ = (Module.AEval'.of A) ((A ^ (m + 1)) w) := by
            rw [pow_succ', Module.End.mul_apply]
            exact hA'of1 ((A ^ m) w)
  have hA'B' : Commute A' B' := by
    calc
      A' * B' = φ (A * B) := by
        dsimp [A', B']
        rw [← map_mul]
      _ = φ (B * A) := by rw [hAB.eq]
      _ = B' * A' := by
        dsimp [A', B']
        rw [map_mul]
  have hXpow' : ∀ n (w : Module.AEval' A), (Polynomial.X ^ n : Polynomial K) • w = (A' ^ n) w := by
    intro n w
    induction n with
    | zero => simp
    | succ n ih =>
        calc
          (Polynomial.X ^ (n + 1) : Polynomial K) • w = (Polynomial.X : Polynomial K) • ((Polynomial.X ^ n : Polynomial K) • w) := by
            rw [pow_succ', ← mul_smul]
          _ = (Polynomial.X : Polynomial K) • ((A' ^ n) w) := by rw [ih]
          _ = A' ((A' ^ n) w) := by rw [← hA']
          _ = (A' ^ (n + 1)) w := by rw [pow_succ', Module.End.mul_apply]
  let Bₓ' : Module.End (Polynomial K) (Module.AEval' A) :=
    { toFun := fun w => B' w
      map_add' := by intro x y; exact B'.map_add x y
      map_smul' := by
        intro c x
        induction c using Polynomial.induction_on' with
        | add c₁ c₂ ih₁ ih₂ =>
            rw [add_smul, map_add, ih₁, ih₂]
            exact (add_smul c₁ c₂ (B' x)).symm
        | monomial n a =>
            calc
              B' ((Polynomial.monomial n a) • x) = B' (a • ((Polynomial.X ^ n : Polynomial K) • x)) := by
                rw [← Polynomial.C_mul_X_pow_eq_monomial, ← smul_smul]
                exact congrArg B' (algebraMap_smul (R := K) (A := Polynomial K) a ((Polynomial.X ^ n : Polynomial K) • x))
              _ = a • (B' ((Polynomial.X ^ n : Polynomial K) • x)) := by
                rw [map_smul]
              _ = a • (B' ((A' ^ n) x)) := by
                rw [hXpow' n x]
              _ = a • ((A' ^ n) (B' x)) := by
                have hc : B' ((A' ^ n) x) = (A' ^ n) (B' x) := by
                  simpa [Module.End.mul_apply] using (LinearMap.congr_fun ((Commute.pow_left hA'B' n).eq.symm) x)
                exact congrArg (fun z : Module.AEval' A => a • z) hc
              _ = (Polynomial.C a * Polynomial.X ^ n) • (B' x) := by
                rw [← hXpow' n (B' x)]
                rw [← algebraMap_smul (R := K) (A := Polynomial K), smul_smul]
                rw [show (algebraMap K (Polynomial K)) a = Polynomial.C a from rfl]
              _ = (Polynomial.monomial n a) • (B' x) := by
                rw [Polynomial.C_mul_X_pow_eq_monomial] }
  have hB' : Bₓ'.restrictScalars (R := K) = B' := by
    ext w
    rfl
  have hann' : ∀ i, (A' ^ e i) (y i) = 0 := by
    intro i
    have h2 : (A' ^ e i) (y i) = (Module.AEval'.of A) ((A ^ e i) (v i)) := by
      rw [← hA'of (e i) (v i)]
      congr 1
    rw [h2, hann i]
    simp
  -- generators in the direct sum
  let lof : ∀ i : ι, fac i →ₗ[Polynomial K] DirectSum ι fac :=
    fun i => DirectSum.lof (Polynomial K) ι fac i
  have hgen : ∀ i (x : fac i), ∃ f : Polynomial K, x = f • gen i := by
    intro i x
    rcases (Submodule.Quotient.mk_surjective ((Polynomial K) ∙ p i ^ e i)) x with ⟨f, rfl⟩
    refine ⟨f, ?_⟩
    change Submodule.Quotient.mk f = f • gen i
    rw [← Submodule.Quotient.mk_smul]
    congr 1
    simp [gen]
  have hspan : ∀ i, Submodule.span (Polynomial K) ({lof i (gen i)} : Set (DirectSum ι fac)) =
      LinearMap.range (lof i) := by
    intro i
    apply le_antisymm
    · rw [Submodule.span_le]
      intro x hx
      rcases hx with rfl
      exact LinearMap.mem_range.mpr ⟨gen i, rfl⟩
    · rw [← Submodule.span_eq (LinearMap.range (lof i))]
      rw [Submodule.span_le]
      rintro x ⟨x', rfl⟩
      rcases hgen i x' with ⟨f, rfl⟩
      rw [map_smul]
      exact Submodule.smul_mem _ f (Submodule.subset_span (by simp))
  have hSup_ds : (⨆ i : ι, Submodule.span (Polynomial K) ({lof i (gen i)} : Set (DirectSum ι fac))) = ⊤ := by
    apply le_antisymm
    · intro x hx
      simp
    · intro x hx
      refine (DirectSum.induction_on x (motive := fun z => z ∈ ⨆ i : ι, Submodule.span (Polynomial K) ({lof i (gen i)} : Set (DirectSum ι fac))) ?_ ?_ ?_)
      · simp
      · intro i x_i
        rcases hgen i x_i with ⟨f, rfl⟩
        change (lof i) (f • gen i) ∈ ⨆ j : ι, Submodule.span (Polynomial K) ({lof j (gen j)} : Set (DirectSum ι fac))
        rw [show (lof i) (f • gen i) = f • (lof i) (gen i) from LinearMap.map_smul (lof i) f (gen i)]
        exact le_iSup (fun j : ι => Submodule.span (Polynomial K) ({lof j (gen j)} : Set (DirectSum ι fac))) i
          (Submodule.smul_mem _ f (Submodule.subset_span (by simp)))
      · intro a b ha hb
        exact add_mem ha hb
  have hspanY : ∀ i, Submodule.span (Polynomial K) ({y i} : Set (Module.AEval' A)) =
      (Submodule.map (eiso.symm : DirectSum ι fac →ₗ[Polynomial K] Module.AEval' A)
        (Submodule.span (Polynomial K) ({lof i (gen i)} : Set (DirectSum ι fac)))) := by
    intro i
    rw [Submodule.map_span]
    rw [show lof i (gen i) = DirectSum.of (β := fac) i (gen i) from rfl]
    simp [y]
  have hSup' : (⨆ i : ι, Submodule.span (Polynomial K) ({y i} : Set (Module.AEval' A))) = ⊤ := by
    apply le_antisymm
    · intro x hx
      simp
    · intro x hx
      rw [← eiso.symm_apply_apply x]
      refine (DirectSum.induction_on (eiso x)
        (motive := fun z : DirectSum ι fac => eiso.symm z ∈ ⨆ i : ι, Submodule.span (Polynomial K) ({y i} : Set (Module.AEval' A)))) ?_ ?_ ?_
      · simp
      · intro i x_i
        rcases hgen i x_i with ⟨f, rfl⟩
        have h1 : eiso.symm (lof i (f • gen i)) = f • y i := by
          calc
            eiso.symm (lof i (f • gen i)) = eiso.symm (f • (lof i) (gen i)) := by
              rw [LinearMap.map_smul (lof i) f (gen i)]
            _ = f • eiso.symm ((lof i) (gen i)) := by rw [eiso.symm.map_smul]
            _ = f • y i := by dsimp [y, lof]; rfl
        change eiso.symm (lof i (f • gen i)) ∈ ⨆ j : ι, Submodule.span (Polynomial K) ({y j} : Set (Module.AEval' A))
        rw [h1]
        exact le_iSup (fun j : ι => Submodule.span (Polynomial K) ({y j} : Set (Module.AEval' A))) i
          (Submodule.smul_mem _ f (Submodule.subset_span (by simp)))
      · intro a b ha hb
        rw [map_add]
        exact add_mem ha hb
  have hcomp : ∀ i j : ι, j ≠ i → ∀ y : fac j, DirectSum.component (Polynomial K) ι fac i (lof j y) = 0 := by
    intro i j hij y
    have h := LinearMap.congr_fun (DirectSum.component_comp_lof (Polynomial K) (ι := ι) (M := fac) i j) y
    rw [dif_neg hij] at h
    simpa using h
  have hcomp_ii : ∀ i (y : fac i), DirectSum.component (Polynomial K) ι fac i (lof i y) = y := by
    intro i y
    have h := LinearMap.congr_fun (DirectSum.component_comp_lof (Polynomial K) (ι := ι) (M := fac) i i) y
    rw [dif_pos rfl] at h
    exact h
  have hIndep_ds : iSupIndep (fun i : ι => LinearMap.range (DirectSum.lof (Polynomial K) ι fac i)) := by
    classical
    rw [iSupIndep_def]
    intro i
    rw [Submodule.disjoint_def]
    intro x hx hx'
    obtain ⟨z, rfl⟩ := LinearMap.mem_range.mp hx
    have key : (⨆ j, ⨆ (_ : j ≠ i), LinearMap.range (DirectSum.lof (Polynomial K) ι fac j)) ≤
        LinearMap.ker (DirectSum.component (Polynomial K) ι fac i) := by
      refine iSup_le fun j => iSup_le fun hj => ?_
      rintro _ ⟨w, rfl⟩
      have h := LinearMap.congr_fun (DirectSum.component_comp_lof (Polynomial K) (ι := ι) (M := fac) i j) w
      rw [dif_neg hj] at h
      exact h
    have hz : DirectSum.component (Polynomial K) ι fac i (DirectSum.lof (Polynomial K) ι fac i z) = 0 :=
      key hx'
    rw [DirectSum.component.lof_self] at hz
    simp [hz]
  have hmapY : ∀ i, Submodule.map (eiso : Module.AEval' A →ₗ[Polynomial K] DirectSum ι fac)
      (Submodule.span (Polynomial K) ({y i} : Set (Module.AEval' A))) =
      Submodule.span (Polynomial K) ({lof i (gen i)} : Set (DirectSum ι fac)) := by
    intro i
    rw [hspanY i]
    rw [Submodule.map_equiv_eq_comap_symm eiso
      (Submodule.map (eiso.symm : DirectSum ι fac →ₗ[Polynomial K] Module.AEval' A)
        (Submodule.span (Polynomial K) ({lof i (gen i)} : Set (DirectSum ι fac))))]
    rw [Submodule.comap_map_eq_of_injective (eiso.symm.injective)
      (Submodule.span (Polynomial K) ({lof i (gen i)} : Set (DirectSum ι fac)))]
  have hIndep' : iSupIndep (fun i : ι => Submodule.span (Polynomial K) ({y i} : Set (Module.AEval' A))) := by
    rw [iSupIndep_def]
    intro i
    rw [Submodule.disjoint_def]
    intro x hx hx'
    apply eiso.injective
    have hx1' : eiso x ∈ Submodule.span (Polynomial K) ({lof i (gen i)} : Set (DirectSum ι fac)) := by
      rw [← hmapY i]
      exact (Submodule.mem_map).mpr ⟨x, hx, rfl⟩
    have hx2' : eiso x ∈ (⨆ j, ⨆ (_ : j ≠ i), Submodule.span (Polynomial K) ({lof j (gen j)} : Set (DirectSum ι fac))) := by
      have hmem : eiso x ∈ Submodule.map (eiso : Module.AEval' A →ₗ[Polynomial K] DirectSum ι fac)
          (⨆ j, ⨆ (_ : j ≠ i), Submodule.span (Polynomial K) ({y j} : Set (Module.AEval' A))) :=
        (Submodule.mem_map).mpr ⟨x, hx', rfl⟩
      simpa [Submodule.map_iSup, hmapY] using hmem
    have hdisj : Disjoint (Submodule.span (Polynomial K) ({lof i (gen i)} : Set (DirectSum ι fac)))
        (⨆ j, ⨆ (_ : j ≠ i), Submodule.span (Polynomial K) ({lof j (gen j)} : Set (DirectSum ι fac))) := by
      have hdi := (iSupIndep_def.mp hIndep_ds) i
      simpa [hspan] using hdi
    simpa using (Submodule.disjoint_def.mp hdisj) (eiso x) hx1' hx2'
  -- sort to Fin r
  let σ₀ : ι ≃ Fin (Fintype.card ι) := Fintype.equivFin ι
  let f : Fin (Fintype.card ι) → ℕ := fun i => e (σ₀.symm i)
  let τ : Fin (Fintype.card ι) ≃ Fin (Fintype.card ι) := Tuple.sort f
  let σ : Fin (Fintype.card ι) ≃ ι := (Fin.revPerm.trans τ).trans σ₀.symm
  let r : ℕ := Fintype.card ι
  let v' : Fin r → Module.AEval' A := fun i => y (σ i)
  let k' : Fin r → ℕ := fun i => e (σ i)
  have hmono : Monotone (f ∘ τ) := Tuple.monotone_sort f
  have hk_anti : Antitone k' := by
    intro i j hij
    dsimp [σ, k', τ]
    exact hmono ((Fin.rev_le_rev).mpr hij)
  have hann_L2 : ∀ i, (Polynomial.X ^ k' i : Polynomial K) • (v' i) = 0 := by
    intro i
    rw [hXpow' (k' i)]
    dsimp [k', v']
    exact hann' (σ i)
  have hIndep_L2 : iSupIndep (fun i : Fin r => Submodule.span (Polynomial K) ({v' i} : Set (Module.AEval' A))) := by
    dsimp [v']
    exact iSupIndep.comp (f := σ) hIndep' (σ.injective)
  have hSup_L2 : (⨆ i : Fin r, Submodule.span (Polynomial K) ({v' i} : Set (Module.AEval' A))) = ⊤ := by
    dsimp [v']
    have hre : (⨆ i : Fin r, Submodule.span (Polynomial K) ({y (σ i)} : Set (Module.AEval' A))) =
        ⨆ j : ι, Submodule.span (Polynomial K) ({y j} : Set (Module.AEval' A)) :=
      σ.iSup_comp (g := fun j : ι => Submodule.span (Polynomial K) ({y j} : Set (Module.AEval' A)))
    rw [hre]
    exact hSup'
  haveI : FiniteDimensional K (Module.AEval' A) := Module.Finite.equiv (Module.AEval'.of A)
  have hL2 : Module.finrank K (Algebra.adjoin K ({A', B'} : Set (Module.End K (Module.AEval' A)))) ≤
      ∑ i : Fin r, k' i := by
    exact (L2.finrank_le_sum (K := K) (W := Module.AEval' A) (r := r) A' B' Bₓ' hA'B' hB' hA' v' k' hk_anti hann_L2 hIndep_L2 hSup_L2)
  have hk_sum : ∑ i : Fin r, k' i = ∑ i : ι, e i := by
    dsimp [k', σ]
    exact (Equiv.sum_comp σ (fun j : ι => e j))
  have hL2' : Module.finrank K (Algebra.adjoin K ({A', B'} : Set (Module.End K (Module.AEval' A)))) ≤
      Module.finrank K V := by
    rw [hsum]
    exact hL2.trans_eq hk_sum
  have hmap : Subalgebra.map φ.toAlgHom (Algebra.adjoin K ({A, B} : Set (Module.End K V))) =
      Algebra.adjoin K ({A', B'} : Set (Module.End K (Module.AEval' A))) := by
    rw [AlgHom.map_adjoin]
    simp [A', B', Set.image_pair]
  have hfin : Module.finrank K (Subalgebra.map φ.toAlgHom (Algebra.adjoin K ({A, B} : Set (Module.End K V)))) =
      Module.finrank K (Algebra.adjoin K ({A, B} : Set (Module.End K V))) := by
    exact (LinearEquiv.finrank_eq (φ.subalgebraMap (Algebra.adjoin K ({A, B} : Set (Module.End K V)))).toLinearEquiv).symm
  rw [← hfin, hmap]
  exact hL2'
lemma core_algClosed (A B : Module.End K V) (hAB : Commute A B) :
    Module.finrank K (Algebra.adjoin K ({A, B} : Set (Module.End K V))) ≤ Module.finrank K V := by
  classical
  have hmain : ∀ n : ℕ, ∀ (W : Type u) [AddCommGroup W] [Module K W] [FiniteDimensional K W],
      Module.finrank K W = n → ∀ (A B : Module.End K W), Commute A B →
        Module.finrank K (Algebra.adjoin K ({A, B} : Set (Module.End K W))) ≤ Module.finrank K W := by
    intro n
    refine Nat.strong_induction_on n ?_
    rintro n' ih W _ _ _ hfinW A B hAB
    by_cases hn0 : Module.finrank K W = 0
    · haveI : Subsingleton W := (Module.finrank_zero_iff.mp hn0)
      have hfin0 : Module.finrank K (Algebra.adjoin K ({A, B} : Set (Module.End K W))) = 0 := by
        haveI : Subsingleton (Module.End K W) := by
          refine ⟨fun f g => ?_⟩
          ext v
          exact Subsingleton.elim (f v) (g v)
        haveI : Subsingleton (Algebra.adjoin K ({A, B} : Set (Module.End K W))) := inferInstance
        exact Module.finrank_zero_of_subsingleton
      rw [hfin0, hn0]
    · have hpos : 0 < Module.finrank K W := by omega
      haveI : Nontrivial W := (Module.finrank_pos_iff).mp hpos
      rcases Module.End.exists_eigenvalue A with ⟨μ, hμ⟩
      let f : Module.End K W := A - μ • (1 : Module.End K W)
      have hAf : Commute A f := by
        dsimp [f]
        exact (Commute.refl A).sub_right ((Commute.one_right A).smul_right μ)
      have hBf : Commute B f := by
        dsimp [f]
        exact hAB.symm.sub_right ((Commute.one_right B).smul_right μ)
      have hfit : ∀ᶠ m in Filter.atTop, IsCompl (f ^ m).ker (f ^ m).range :=
        LinearMap.eventually_isCompl_ker_pow_range_pow f
      rcases (Filter.eventually_atTop.1 hfit) with ⟨m, hm⟩
      let m0 := max m 1
      have hm0 : m ≤ m0 := le_max_left _ _
      have hm0' : 1 ≤ m0 := le_max_right _ _
      have hcomp : IsCompl (f ^ m0).ker (f ^ m0).range := hm m0 hm0
      let K0 : Submodule K W := (f ^ m0).ker
      let R0 : Submodule K W := (f ^ m0).range
      have hAK : ∀ x ∈ K0, A x ∈ K0 := by
        intro x hx
        have hAcomm : Commute A (f ^ m0) := hAf.pow_right m0
        have hA : A x ∈ (f ^ m0).ker := by
          rw [LinearMap.mem_ker] at hx ⊢
          have hcompA : (f ^ m0) (A x) = A ((f ^ m0) x) := by
            have := congrArg (fun T : Module.End K W => T x) hAcomm.eq
            simpa using this.symm
          rw [hcompA, hx, map_zero]
        simpa [K0] using hA
      have hBK : ∀ x ∈ K0, B x ∈ K0 := by
        intro x hx
        have hBcomm : Commute B (f ^ m0) := hBf.pow_right m0
        have hB : B x ∈ (f ^ m0).ker := by
          rw [LinearMap.mem_ker] at hx ⊢
          have hcompB : (f ^ m0) (B x) = B ((f ^ m0) x) := by
            have := congrArg (fun T : Module.End K W => T x) hBcomm.eq
            simpa using this.symm
          rw [hcompB, hx, map_zero]
        simpa [K0] using hB
      have hAR : ∀ x ∈ R0, A x ∈ R0 := by
        intro x hx
        rw [LinearMap.mem_range] at hx ⊢
        rcases hx with ⟨y, hy⟩
        have hAcomm : Commute A (f ^ m0) := hAf.pow_right m0
        refine ⟨A y, ?_⟩
        rw [← hy]
        have hcompA : (f ^ m0) (A y) = A ((f ^ m0) y) := by
          have := congrArg (fun T : Module.End K W => T y) hAcomm.eq
          simpa using this.symm
        exact hcompA
      have hBR : ∀ x ∈ R0, B x ∈ R0 := by
        intro x hx
        rw [LinearMap.mem_range] at hx ⊢
        rcases hx with ⟨y, hy⟩
        have hBcomm : Commute B (f ^ m0) := hBf.pow_right m0
        refine ⟨B y, ?_⟩
        rw [← hy]
        have hcompB : (f ^ m0) (B y) = B ((f ^ m0) y) := by
          have := congrArg (fun T : Module.End K W => T y) hBcomm.eq
          simpa using this.symm
        exact hcompB
      by_cases hR0 : R0 = ⊥
      · have hnil : IsNilpotent f := by
          refine ⟨m0, ?_⟩
          have : (f ^ m0).range = ⊥ := by simpa [R0] using hR0
          exact LinearMap.range_eq_bot.mp this
        have hA : A = f + μ • (1 : Module.End K W) := by simp [f]
        have hadj : Algebra.adjoin K ({A, B} : Set (Module.End K W)) =
            Algebra.adjoin K ({f, B} : Set (Module.End K W)) := by
          apply le_antisymm <;> refine Algebra.adjoin_le ?_ <;> rintro x (rfl | rfl)
          · rw [hA]; exact add_mem (Algebra.subset_adjoin (by simp)) (Subalgebra.smul_mem _ (one_mem _) _)
          · exact Algebra.subset_adjoin (by simp)
          · exact sub_mem (Algebra.subset_adjoin (by simp)) (Subalgebra.smul_mem _ (one_mem _) _)
          · exact Algebra.subset_adjoin (by simp)
        rw [hadj]
        exact nilpotent_core f B hBf.symm hnil
      · have hK0ne : K0 ≠ ⊥ := by
          have hμ' : ∃ v : W, v ≠ 0 ∧ A v = μ • v := by
            change A.eigenspace μ ≠ ⊥ at hμ
            rcases (Submodule.ne_bot_iff (A.eigenspace μ)).mp hμ with ⟨v, hv, hv0⟩
            exact ⟨v, hv0, (Module.End.mem_eigenspace_iff).mp hv⟩
          rcases hμ' with ⟨v, hv, hvμ⟩
          have hfv : f v = 0 := by
            dsimp [f]
            simp [hvμ]
          have hvK : v ∈ K0 := by
            change v ∈ (f ^ m0).ker
            rw [LinearMap.mem_ker]
            rw [show m0 = (m0 - 1) + 1 from (Nat.sub_add_cancel hm0').symm, pow_succ]
            simp [hfv]
          intro hbot
          have : v = 0 := by
            have hvbot : v ∈ (⊥ : Submodule K W) := by
              simpa [hbot] using hvK
            simpa using hvbot
          exact hv this
        have hR0pos : 0 < Module.finrank K R0 := by
          have : Module.finrank K R0 ≠ 0 := by
            intro h0
            exact hR0 (Submodule.finrank_eq_zero.mp h0)
          omega
        have hK0pos : 0 < Module.finrank K K0 := by
          have : Module.finrank K K0 ≠ 0 := by
            intro h0
            exact hK0ne (Submodule.finrank_eq_zero.mp h0)
          omega
        have hsum : Module.finrank K K0 + Module.finrank K R0 = Module.finrank K W :=
          Submodule.finrank_add_eq_of_isCompl hcomp
        have hK0lt : Module.finrank K K0 < n' := by omega
        have hR0lt : Module.finrank K R0 < n' := by omega
        let AK : Module.End K K0 := A.restrict hAK
        let BK : Module.End K K0 := B.restrict hBK
        let AR : Module.End K R0 := A.restrict hAR
        let BR : Module.End K R0 := B.restrict hBR
        have hABK : Commute AK BK := by
          ext x
          have h : A (B (x : W)) = B (A (x : W)) := by
            have := congrArg (fun T : Module.End K W => T (x : W)) hAB
            simpa using this
          simpa [AK, BK, LinearMap.restrict_apply] using h
        have hABR : Commute AR BR := by
          ext x
          have h : A (B (x : W)) = B (A (x : W)) := by
            have := congrArg (fun T : Module.End K W => T (x : W)) hAB
            simpa using this
          simpa [AR, BR, LinearMap.restrict_apply] using h
        have ihK := ih (Module.finrank K K0) hK0lt K0 rfl AK BK hABK
        have ihR := ih (Module.finrank K R0) hR0lt R0 rfl AR BR hABR
        have htwo : Module.finrank K (Algebra.adjoin K ({A, B} : Set (Module.End K W))) ≤
            Module.finrank K (Algebra.adjoin K ({AK, BK} : Set (Module.End K K0))) +
              Module.finrank K (Algebra.adjoin K ({AR, BR} : Set (Module.End K R0))) :=
          finrank_twoBlock A B hAB hcomp hAK hBK hAR hBR
        omega
  exact hmain (Module.finrank K V) V rfl A B hAB

end Core

/--
**Gerstenhaber's theorem** [Ger61]: if $A$ and $B$ are commuting $n \times n$
matrices over a field $K$, then the unital $K$-algebra $K[A, B]$ they generate
has dimension at most $n$.
-/
@[category research solved, AMS 15 16]
theorem finrank_adjoin_pair_le (A B : Matrix (Fin n) (Fin n) K) (hAB : Commute A B) :
    Module.finrank K (Algebra.adjoin K {A, B}) ≤ n := by
  let Kbar := AlgebraicClosure K
  let Abar : Matrix (Fin n) (Fin n) Kbar := A.map (algebraMap K Kbar)
  let Bbar : Matrix (Fin n) (Fin n) Kbar := B.map (algebraMap K Kbar)
  have hbc := finrank_baseChange_le (K := K) (L := Kbar) (n := n) A B
  have htr := finrank_adjoin_transfer (K := Kbar) (n := n) Abar Bbar
  have hABbar0 : Commute Abar Bbar := by
    exact Commute.map hAB (RingHom.mapMatrix (algebraMap K Kbar))
  have hABbar : Commute (linAlgEquiv Kbar n Abar) (linAlgEquiv Kbar n Bbar) := by
    exact Commute.map hABbar0 (linAlgEquiv Kbar n)
  have hcore := Core.core_algClosed (K := Kbar) (V := Fin n → Kbar)
    (linAlgEquiv Kbar n Abar) (linAlgEquiv Kbar n Bbar) hABbar
  have hfin : Module.finrank Kbar (Fin n → Kbar) = n := by
    rw [Module.finrank_pi]
    simp
  calc
    Module.finrank K (Algebra.adjoin K ({A, B} : Set (Matrix (Fin n) (Fin n) K))) ≤
        Module.finrank Kbar (Algebra.adjoin Kbar
          ({Abar, Bbar} : Set (Matrix (Fin n) (Fin n) Kbar))) := by
      simpa [Abar, Bbar] using hbc
    _ = Module.finrank Kbar (Algebra.adjoin Kbar
          ({linAlgEquiv Kbar n Abar, linAlgEquiv Kbar n Bbar} : Set (Module.End Kbar (Fin n → Kbar)))) := by
      simpa [Abar, Bbar] using htr
    _ ≤ Module.finrank Kbar (Fin n → Kbar) := hcore
    _ = n := hfin

/--
**The Gerstenhaber problem**: if $A$, $B$, and $C$ are pairwise commuting
$n \times n$ matrices over a field $K$, is the dimension of the unital
$K$-algebra $K[A, B, C]$ they generate always at most $n$?
-/
@[category research open, AMS 15 16]
theorem finrank_adjoin_triple_le :
    answer(sorry) ↔
      ∀ (K : Type*) [Field K] (n : ℕ) (A B C : Matrix (Fin n) (Fin n) K),
        ({A, B, C} : Set (Matrix (Fin n) (Fin n) K)).Pairwise Commute →
          Module.finrank K (Algebra.adjoin K {A, B, C}) ≤ n := by
  sorry

/--
The analogue of Gerstenhaber's theorem fails for four pairwise commuting matrices:
over any field there are four pairwise commuting $4 \times 4$ matrices generating a unital
algebra of dimension greater than $4$. The standard example is
$e_{13}, e_{14}, e_{23}, e_{24}$, whose pairwise products all vanish, so the algebra
they generate has dimension $5$.
-/
@[category research solved, AMS 15 16]
theorem exists_finrank_adjoin_quadruple_gt (K : Type*) [Field K] :
    ∃ A B C D : Matrix (Fin 4) (Fin 4) K,
      ({A, B, C, D} : Set (Matrix (Fin 4) (Fin 4) K)).Pairwise Commute ∧
      4 < Module.finrank K (Algebra.adjoin K {A, B, C, D}) := by
  refine ⟨Matrix.single 0 2 1, Matrix.single 0 3 1, Matrix.single 1 2 1, Matrix.single 1 3 1,
    ?_, ?_⟩
  · -- All pairwise products vanish: the column index of one factor is `2` or `3` and the row
    -- index of the other is `0` or `1`.
    intro x hx y hy _
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx hy
    rcases hx with rfl | rfl | rfl | rfl <;> rcases hy with rfl | rfl | rfl | rfl <;>
      first
      | exact Commute.refl _
      | exact (show _ * _ = _ * _ by simp (disch := decide) [Matrix.single_mul_single_of_ne])
  · -- `1, e₁₃, e₁₄, e₂₃, e₂₄` are linearly independent elements of the subalgebra.
    set S := Algebra.adjoin K ({Matrix.single 0 2 1, Matrix.single 0 3 1, Matrix.single 1 2 1,
      Matrix.single 1 3 1} : Set (Matrix (Fin 4) (Fin 4) K)) with hS
    let v : Fin 5 → Matrix (Fin 4) (Fin 4) K :=
      ![1, Matrix.single 0 2 1, Matrix.single 0 3 1, Matrix.single 1 2 1, Matrix.single 1 3 1]
    have hv : ∀ i, v i ∈ S := by
      intro i
      fin_cases i
      · exact one_mem S
      all_goals exact Algebra.subset_adjoin (by simp [v])
    have hw : LinearIndependent K fun i => (⟨v i, hv i⟩ : S) := by
      rw [Fintype.linearIndependent_iff]
      intro g hg i
      have h := congrArg Subtype.val hg
      simp only [Subalgebra.coe_zero] at h
      change ∑ j, g j • v j = 0 at h
      have e : ∀ a b : Fin 4, (∑ j, g j • v j) a b = 0 := fun a b => by rw [h]; rfl
      simp only [Matrix.sum_apply, Matrix.smul_apply, Fin.sum_univ_five, v] at e
      have e00 := e 0 0
      have e02 := e 0 2
      have e03 := e 0 3
      have e12 := e 1 2
      have e13 := e 1 3
      simp at e00 e02 e03 e12 e13
      fin_cases i <;> simp_all
    have := hw.fintype_card_le_finrank
    simp only [Fintype.card_fin] at this
    omega

end Gerstenhaber
